import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ExternalLink, Landmark, Newspaper, Search, Scale, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export const Route = createFileRoute("/noticias")({
  head: () => ({ meta: [
    { title: "Noticias para Negocios — Nüva One" },
    { name: "description", content: "Actualidad económica, tributaria, regulatoria y empresarial para negocios y PyMEs chilenas, con fuentes oficiales y contexto práctico." },
  ]}),
  component: Noticias,
});

type NewsItem = { category: string; date: string; title: string; summary: string; detail: string; impact: string; href: string; source: string };
const NEWS: NewsItem[] = [
  { category: "Economía", date: "9 sep 2026", title: "Banco Central publica el IPoM de septiembre", summary: "El escenario central proyecta un crecimiento del PIB 2026 de 0,25%-0,75% y mantiene el foco en inflación y demanda interna.", detail: "El informe reúne antecedentes de actividad, consumo, inversión, inflación y condiciones financieras.", impact: "Revisar precios, costos, inventario, inversión y liquidez bajo distintos escenarios de demanda.", href: "https://www.bcentral.cl/es/web/banco-central/contenido/-/details/prensa/nota-de-prensa/bcch-publica-ipom-septiembre-2026", source: "Banco Central de Chile" },
  { category: "PyMEs", date: "7 sep 2026", title: "Agenda ProPyme aborda trámites, financiamiento y liquidez", summary: "El Ministerio de Economía informó avances de una agenda orientada a desafíos de las MiPymes.", detail: "La instancia reúne al sector público y gremios para trabajar propuestas tributarias, regulatorias e institucionales.", impact: "Seguir cambios que puedan modificar costos de cumplimiento, acceso a financiamiento o condiciones para operar.", href: "https://www.economia.gob.cl/2026/09/07/ministro-mas-compromete-avances-en-agenda-legislativa-para-fortalecer-a-las-mipymes.htm", source: "Ministerio de Economía" },
  { category: "Impuestos", date: "1 sep 2026", title: "Nueva Declaración Jurada N.º 1965 para contenido digital", summary: "El SII creó una nueva DJ anual para personas y empresas que operan plataformas de contenido digital. Aplicará desde Operación Renta 2027.", detail: "La obligación alcanza a entidades que gestionen, administren o intermedien ingresos mediante medios digitales.", impact: "Revisar registros, ingresos y documentación tributaria si tu negocio participa en esta actividad.", href: "https://www.sii.cl/noticias/2026/010926noti02pcr.htm", source: "Servicio de Impuestos Internos" },
  { category: "Empresas", date: "28 ago 2026", title: "Más de 140 mil empresas constituidas entre enero y julio", summary: "El Ministerio de Economía informó 140.412 constituciones acumuladas durante los primeros siete meses de 2026.", detail: "El 91,9% de las constituciones de julio utilizó el Registro de Empresas y Sociedades.", impact: "Más empresas también significa nuevos competidores, proveedores y potenciales clientes.", href: "https://www.economia.gob.cl/2026/08/28/informe-de-creacion-de-empresas-y-cooperativas-julio-2026.htm", source: "Ministerio de Economía" },
  { category: "Innovación", date: "11 sep 2026", title: "Corfo impulsa soluciones de IA para agilizar patentes municipales", summary: "El Ministerio de Economía informó un programa de Corfo orientado a desarrollar soluciones de inteligencia artificial para agilizar procesos de patentes municipales.", detail: "La iniciativa aborda un proceso relevante para la formalización y operación de negocios.", impact: "La digitalización de trámites puede abrir oportunidades y reducir costos de gestión empresarial.", href: "https://www.economia.gob.cl/2026/09/11/corfo-lanza-programa-de-bienes-publicos-para-el-desarrollo-de-soluciones-de-ia-que-agilicen-patentes-municipales.htm", source: "Ministerio de Economía" },
  { category: "Tributación", date: "15 sep 2026", title: "SII fortalece colaboración en materia tributaria", summary: "El SII informó un convenio con el Instituto Chileno de Derecho Tributario para estudio, capacitación e investigación.", detail: "La colaboración busca fortalecer el conocimiento técnico en Derecho Tributario.", impact: "Para decisiones tributarias, priorizar siempre la normativa y comunicaciones oficiales.", href: "https://www.sii.cl/noticias/2026/150926noti01srm.htm", source: "Servicio de Impuestos Internos" },
  { category: "Financiamiento", date: "7 sep 2026", title: "ProPyme pone el financiamiento y la liquidez en el centro", summary: "La agenda ProPyme incorpora acceso al financiamiento y liquidez entre los desafíos abordados junto a representantes de las MiPymes.", detail: "El foco permite seguir futuras medidas e instrumentos que puedan incidir en las condiciones financieras.", impact: "Revisar necesidades de capital de trabajo y mantener identificadas alternativas de financiamiento.", href: "https://www.economia.gob.cl/2026/09/07/ministro-mas-compromete-avances-en-agenda-legislativa-para-fortalecer-a-las-mipymes.htm", source: "Ministerio de Economía" },
];
const SOURCES = [
  { name: "SII", category: "Impuestos", description: "Noticias tributarias, declaraciones, facturación y obligaciones.", href: "https://www.sii.cl/noticias/", icon: Scale },
  { name: "Banco Central", category: "Mercado", description: "Inflación, TPM, actividad, inversión y entorno financiero.", href: "https://www.bcentral.cl/", icon: TrendingUp },
  { name: "Ministerio de Economía", category: "Economía", description: "Medidas, programas y novedades para empresas.", href: "https://www.economia.gob.cl/", icon: Landmark },
  { name: "CORFO", category: "Innovación", description: "Programas, convocatorias y oportunidades de innovación.", href: "https://www.corfo.cl/", icon: Newspaper },
  { name: "SERCOTEC", category: "PyMEs", description: "Programas, capacitación y apoyo para emprendedores.", href: "https://www.sercotec.cl/", icon: Newspaper },
];
const CATEGORIES = ["Todas", "Economía", "PyMEs", "Impuestos", "Tributación", "Empresas", "Innovación", "Financiamiento"];

function Noticias() {
  const [activeCategory, setActiveCategory] = useState("Todas");
  const [searchTerm, setSearchTerm] = useState("");
  const filteredNews = useMemo(() => { const term = searchTerm.trim().toLowerCase(); return NEWS.filter((item) => { const category = activeCategory === "Todas" || item.category === activeCategory; const search = !term || `${item.title} ${item.summary} ${item.detail} ${item.impact} ${item.source}`.toLowerCase().includes(term); return category && search; }); }, [activeCategory, searchTerm]);
  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-40 border-b bg-background/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link to="/" className="font-semibold tracking-tight">Nüva One</Link><div className="flex items-center gap-2"><Link to="/foro"><Button variant="ghost" size="sm">Comunidad</Button></Link><Link to="/negocios"><Button variant="outline" size="sm">Red de negocios</Button></Link></div></div></header>
    <main>
      <section className="relative isolate min-h-[min(720px,82vh)] overflow-hidden bg-[#080809] text-white">
        <video className="absolute inset-0 h-full w-full object-cover" src="/news/noticias-pestel.mp4" autoPlay loop muted playsInline preload="metadata" aria-hidden="true" />
        <div className="absolute inset-0 bg-gradient-to-r from-[#080809]/90 via-[#080809]/55 to-[#080809]/25" /><div className="absolute inset-0 bg-gradient-to-t from-[#080809] via-transparent to-[#080809]/20" />
        <div className="relative z-10 mx-auto flex min-h-[min(720px,82vh)] max-w-7xl items-end px-6 pb-14 pt-32 md:px-10 md:pb-20"><div className="max-w-4xl"><Badge variant="outline" className="border-white/25 bg-white/10 text-white backdrop-blur">NOTICIAS PARA NEGOCIOS · CHILE</Badge><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.94] tracking-[-.045em] sm:text-7xl lg:text-[clamp(4.5rem,7vw,7.5rem)]">Todo lo que pasa afuera. <span className="text-[#E6C687]">Importa adentro.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/80 sm:text-lg">Política, economía, sociedad, tecnología, medioambiente y regulación reunidos en un solo contexto para tu empresa.</p><div className="mt-7 flex flex-wrap gap-2">{["POLÍTICO","ECONÓMICO","SOCIAL","TECNOLÓGICO","ECOLÓGICO","LEGAL"].map((x) => <span key={x} className="rounded-full border border-white/15 bg-black/25 px-3 py-1.5 text-[10px] font-bold tracking-[.16em] text-white/75 backdrop-blur">{x}</span>)}</div></div></div>
      </section>
      <div className="mx-auto max-w-7xl px-6 py-10 sm:py-14">
        <section className="max-w-4xl"><Badge variant="secondary">Centro de actualidad empresarial</Badge><h2 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">Entiende lo que está pasando. <span className="text-primary">Decide con contexto.</span></h2><p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">Un centro de actualidad empresarial para seguir economía, impuestos, regulación, financiamiento, innovación y oportunidades que pueden impactar la operación de tu negocio.</p><div className="mt-6 flex flex-wrap gap-3"><Badge variant="outline">Actualizado: 18 sep 2026</Badge><Badge variant="outline">Fuentes oficiales</Badge><Badge variant="outline">Contexto para PyMEs</Badge></div></section>
        <section className="mt-10 grid gap-4 sm:grid-cols-3" aria-label="Contexto económico"><Card><CardContent className="p-5"><p className="text-xs uppercase tracking-widest text-muted-foreground">Crecimiento 2026</p><p className="mt-2 text-3xl font-bold">0,25%-0,75%</p><p className="mt-1 text-sm text-muted-foreground">Rango central del IPoM de septiembre.</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs uppercase tracking-widest text-muted-foreground">Inflación</p><p className="mt-2 text-3xl font-bold">≈ 4%</p><p className="mt-1 text-sm text-muted-foreground">Entorno descrito por el Banco Central.</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-xs uppercase tracking-widest text-muted-foreground">Empresas 2026</p><p className="mt-2 text-3xl font-bold">140.412</p><p className="mt-1 text-sm text-muted-foreground">Constituciones acumuladas entre enero y julio.</p></CardContent></Card></section>
        <section className="mt-12 rounded-2xl border bg-card p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-medium text-primary">Briefing ejecutivo</p><h2 className="mt-1 text-2xl font-bold">Lo que conviene mirar esta semana</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">No todas las noticias tienen el mismo impacto. Aquí las agrupamos por el tipo de decisión empresarial que pueden afectar.</p></div><Link to="/dashboard"><Button variant="outline">Ver mi operación <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div><div className="mt-6 grid gap-4 md:grid-cols-3"><Briefing title="Caja y costos" text="El escenario macro importa para demanda, precios, inversión y planificación de liquidez." /><Briefing title="Cumplimiento" text="Las novedades tributarias deben contrastarse con la fuente oficial antes de actuar." /><Briefing title="Crecimiento" text="La creación de empresas, innovación y programas públicos pueden abrir nuevos mercados y oportunidades." /></div></section>
        <section className="mt-14" aria-label="Más noticias que pueden importar a tu empresa"><p className="text-sm font-medium text-primary">Actualidad verificada</p><h2 className="mt-1 text-2xl font-bold">Más noticias que pueden importar a tu empresa</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Filtra por tema y revisa las novedades que pueden tener relación con tu operación.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} placeholder="Buscar noticias, temas o fuentes..." aria-label="Buscar noticias" className="h-11 w-full rounded-full border bg-background pl-10 pr-4 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20" /></label>{(searchTerm || activeCategory !== "Todas") && <button type="button" onClick={() => { setSearchTerm(""); setActiveCategory("Todas"); }} className="h-11 rounded-full border px-4 text-sm font-medium text-muted-foreground hover:border-primary/50 hover:text-foreground">Limpiar filtros</button>}</div><div className="mt-4 flex flex-wrap gap-2" role="group" aria-label="Filtrar noticias por categoría">{CATEGORIES.map((category) => <button key={category} type="button" aria-pressed={activeCategory === category} onClick={() => setActiveCategory(category)} className={`rounded-full border px-4 py-2 text-sm font-medium transition-all hover:-translate-y-0.5 hover:border-primary/50 hover:bg-primary/5 ${activeCategory === category ? "border-primary bg-primary text-primary-foreground shadow-sm" : "bg-background text-muted-foreground"}`}>{category}</button>)}</div><div className="mt-7 flex items-center justify-between"><p className="text-sm text-muted-foreground">{filteredNews.length} {filteredNews.length === 1 ? "noticia encontrada" : "noticias encontradas"}{activeCategory !== "Todas" ? ` · ${activeCategory}` : ""}</p>{activeCategory !== "Todas" && <button type="button" onClick={() => setActiveCategory("Todas")} className="text-sm font-medium text-primary hover:underline">Ver todas</button>}</div>{filteredNews.length ? <div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filteredNews.map((item) => <NewsCard key={item.title} item={item} />)}</div> : <Card className="mt-5"><CardContent className="p-8 text-center"><p className="font-semibold">No hay noticias en esta categoría todavía.</p><p className="mt-2 text-sm text-muted-foreground">Vuelve a “Todas” para revisar la cobertura disponible.</p></CardContent></Card>}</section>
        <section className="mt-14"><p className="text-sm font-medium text-primary">Lectura empresarial</p><h2 className="mt-1 text-2xl font-bold">De la noticia a la decisión</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Cada noticia puede mirarse desde cuatro dimensiones operativas.</p><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Lens number="01" title="Ventas" text="¿Puede cambiar la demanda, los precios o el comportamiento del cliente?" /><Lens number="02" title="Caja" text="¿Afecta costos, financiamiento, pagos o necesidades de liquidez?" /><Lens number="03" title="Operación" text="¿Cambia procesos, inventario, proveedores o cumplimiento?" /><Lens number="04" title="Estrategia" text="¿Aparece una oportunidad, riesgo o nuevo escenario competitivo?" /></div></section>
        <section className="mt-14"><p className="text-sm font-medium text-primary">Fuentes que importan</p><h2 className="mt-1 text-2xl font-bold">Un punto de entrada a la información oficial</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{SOURCES.map(({ name, category, description, href, icon: Icon }) => <Card key={name}><CardContent className="p-5"><Icon className="h-5 w-5 text-primary" /><Badge variant="outline" className="mt-4">{category}</Badge><h3 className="mt-3 font-semibold">{name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p><a href={href} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-sm font-medium">Visitar fuente <ExternalLink className="ml-2 h-4 w-4" /></a></CardContent></Card>)}</div></section>
        <section className="mt-14 rounded-2xl border bg-card p-7 sm:p-9"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-primary">De la información a la acción</p><h2 className="mt-1 text-xl font-semibold">Conecta las noticias con la realidad de tu negocio.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Después de revisar una novedad, vuelve a Nüva One para analizar ventas, caja, inventario, clientes y resultados con el contexto de tu propia operación.</p></div><Link to="/dashboard"><Button>Ir al dashboard <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></section>
      </div>
    </main>
  </div>;
}
function NewsCard({ item }: { item: NewsItem }) { return <Card className="h-full transition-shadow hover:shadow-elegant"><CardContent className="flex h-full flex-col p-6"><div className="flex items-center justify-between gap-3"><Badge variant="outline">{item.category}</Badge><span className="text-xs text-muted-foreground">{item.date}</span></div><h3 className="mt-4 text-xl font-semibold leading-tight">{item.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.summary}</p><div className="mt-4 rounded-lg bg-muted/40 p-3"><p className="text-xs font-semibold uppercase tracking-wide">En detalle</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.detail}</p></div><div className="mt-4 rounded-lg border border-primary/20 bg-primary/5 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Para tu negocio</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.impact}</p></div><a href={item.href} target="_blank" rel="noreferrer" className="mt-auto pt-5 inline-flex items-center text-sm font-medium text-primary">Fuente oficial · {item.source} <ExternalLink className="ml-2 h-4 w-4" /></a></CardContent></Card>; }
function Briefing({ title, text }: { title: string; text: string }) { return <div className="rounded-xl border p-5"><p className="font-semibold">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function Lens({ number, title, text }: { number: string; title: string; text: string }) { return <div className="rounded-xl border p-5"><p className="text-xs font-bold tracking-[.2em] text-primary">{number}</p><h3 className="mt-2 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
