import { createFileRoute, redirect } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Bot, Building2, CheckCircle2, CircleDollarSign, Gauge, LogOut, RefreshCw, ShieldCheck, Sparkles, TrendingUp, Users, XCircle, Database, BarChart3, Target, Clock3, Zap, AlertCircle, Eye } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

type Telemetry = { events: number; active_users: number; active_businesses: number; errors: number; ai_events: number; avg_duration_ms: number | null } | null;
type Metrics = { users: number; businesses: number; memberships: number; customers: number; products: number; sales: number; transactions: number; quotes: number; ai_conversations: number; ai_messages: number; income: number; expenses: number; generated_at: string; telemetry?: Telemetry };

export const Route = createFileRoute("/owner")({
  ssr: false,
  beforeLoad: async () => {
    await supabase.auth.refreshSession();
    const { data } = await supabase.auth.getUser();
    if (!data.user) throw redirect({ to: "/auth" });
    if (data.user.app_metadata?.platform_role !== "owner") throw redirect({ to: "/" });
  },
  component: OwnerConsole,
});

async function loadMetrics(): Promise<Metrics> {
  const { data, error } = await supabase.functions.invoke("owner-metrics", { body: {} });
  if (error) throw new Error("No se pudieron cargar los indicadores de Nüva.");
  return data as Metrics;
}

const clp = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });
const num = (value: number) => value.toLocaleString("es-CL");

function OwnerConsole() {
  const [metrics, setMetrics] = useState<Metrics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [section, setSection] = useState<"overview" | "growth" | "product" | "ia" | "economia" | "observability">("overview");
  const refresh = async () => { setLoading(true); setError(null); try { setMetrics(await loadMetrics()); } catch (err) { setError(err instanceof Error ? err.message : "Error inesperado"); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  const net = useMemo(() => (metrics?.income ?? 0) - (metrics?.expenses ?? 0), [metrics]);
  const tabs = [["overview", "Overview", Gauge], ["growth", "Growth", TrendingUp], ["product", "Product Health", Activity], ["observability", "Observability", Zap], ["ia", "Nüva IA", Bot], ["economia", "Economía", CircleDollarSign]] as const;
  return <div className="min-h-screen bg-[#07070c] px-4 py-6 text-white sm:px-8"><div className="mx-auto max-w-[1440px]">
    <header className="mb-6 overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-br from-white/[0.075] via-white/[0.035] to-transparent p-6 shadow-2xl shadow-black/30 backdrop-blur-xl sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-3 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.28em] text-cyan-200/70"><ShieldCheck className="h-4 w-4" /> Private Owner Console</div><h1 className="text-3xl font-semibold tracking-tight sm:text-5xl">Nüva Command Center</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/50">La vista privada para entender el estado real de Nüva One: adopción, actividad, IA, economía y salud del producto.</p></div><div className="flex shrink-0 gap-2"><button onClick={() => void refresh()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-medium transition hover:bg-white/10 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /> Actualizar</button><button onClick={() => void supabase.auth.signOut()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-medium transition hover:bg-white/10"><LogOut className="h-4 w-4" /> Salir</button></div></div><nav className="mt-7 flex gap-1 overflow-x-auto border-t border-white/8 pt-4">{tabs.map(([id,label,Icon]) => <button key={id} onClick={() => setSection(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm transition ${section === id ? "bg-white/10 text-white" : "text-white/45 hover:bg-white/5 hover:text-white/80"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav></header>
    {error ? <div className="mb-6 flex items-center gap-3 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-100"><XCircle className="h-5 w-5 shrink-0" />{error}</div> : null}
    {section === "overview" && <Overview metrics={metrics} loading={loading} />}{section === "growth" && <Growth metrics={metrics} loading={loading} />}{section === "product" && <ProductHealth metrics={metrics} />}{section === "observability" && <Observability metrics={metrics} loading={loading} />}{section === "ia" && <IA metrics={metrics} loading={loading} />}{section === "economia" && <Economia metrics={metrics} loading={loading} net={net} />}
    <footer className="mt-8 flex flex-col gap-2 border-t border-white/8 pt-5 text-xs text-white/30 sm:flex-row sm:items-center sm:justify-between"><span>Datos agregados de plataforma · sin exposición de contenido privado de PYMEs</span><span>Última lectura: {metrics ? new Date(metrics.generated_at).toLocaleString("es-CL") : "—"}</span></footer>
  </div></div>;
}

function Overview({ metrics, loading }: { metrics: Metrics | null; loading: boolean }) { const cards = [["Usuarios", metrics?.users ?? 0, Users], ["Empresas", metrics?.businesses ?? 0, Building2], ["Membresías", metrics?.memberships ?? 0, Users], ["Clientes", metrics?.customers ?? 0, Users], ["Productos", metrics?.products ?? 0, Database], ["Ventas en plataforma", metrics?.sales ?? 0, Activity], ["Transacciones", metrics?.transactions ?? 0, BarChart3], ["Cotizaciones", metrics?.quotes ?? 0, Target], ["Conversaciones IA", metrics?.ai_conversations ?? 0, Bot]] as const; return <><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{cards.map(([label,value,Icon]) => <MetricCard key={label} label={label} value={value} Icon={Icon} loading={loading} />)}</section><section className="mt-5 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Panel icon={Sparkles} title="Operating Pulse de Nüva" subtitle="Actividad agregada de toda la plataforma."><div className="grid gap-3 sm:grid-cols-3"><Insight label="Ventas en plataforma" value={metrics ? num(metrics.sales) : "—"} detail="actividad de clientes" /><Insight label="Intensidad IA" value={metrics && metrics.ai_conversations ? metrics.ai_messages / metrics.ai_conversations : 0} detail="mensajes / conversación" /><Insight label="Membresías / empresa" value={metrics && metrics.businesses ? metrics.memberships / metrics.businesses : 0} detail="promedio actual" /></div></Panel><Panel icon={CheckCircle2} title="Seguridad del panel" subtitle="Controles actuales"><Status label="Sesión autenticada" ok /><Status label="platform_role = owner" ok /><Status label="Métricas agregadas" ok /><Status label="RPC propietario" ok /></Panel></section></>; }

function Observability({ metrics, loading }: { metrics: Metrics | null; loading: boolean }) { const t = metrics?.telemetry; const hasData = Boolean(t); const cards = [["Eventos · 24h", t?.events ?? 0, Activity], ["Usuarios activos", t?.active_users ?? 0, Users], ["PYMEs activas", t?.active_businesses ?? 0, Building2], ["Errores", t?.errors ?? 0, AlertCircle], ["Eventos IA", t?.ai_events ?? 0, Bot]] as const; return <section className="space-y-5"><div className="rounded-[26px] border border-cyan-200/10 bg-gradient-to-br from-cyan-200/[0.07] via-white/[0.035] to-transparent p-6 shadow-2xl shadow-black/20"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.24em] text-cyan-200/70"><Zap className="h-4 w-4" /> Live Product Telemetry</div><h2 className="mt-2 text-2xl font-semibold">Observability de Nüva One</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/45">Vista técnica privada para saber si Nüva está siendo usada, rápida y estable. Ventana: últimas 24 horas.</p></div><div className={`inline-flex w-fit items-center gap-2 rounded-full border px-3 py-2 text-xs ${hasData ? "border-emerald-300/15 bg-emerald-300/10 text-emerald-100" : "border-amber-300/15 bg-amber-300/10 text-amber-100"}`}><span className={`h-2 w-2 rounded-full ${hasData ? "bg-emerald-300" : "bg-amber-300"}`} />{hasData ? "Telemetría conectada" : "Esperando migración de datos"}</div></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label,value,Icon]) => <MetricCard key={label} label={label} value={value} Icon={Icon} loading={loading} />)}</div><div className="grid gap-5 lg:grid-cols-2"><Panel icon={Gauge} title="Performance" subtitle="Web Vitals / latencia"><div className="grid gap-3 sm:grid-cols-2"><Insight label="Duración media" value={t?.avg_duration_ms != null ? `${Math.round(t.avg_duration_ms)} ms` : "—"} detail="eventos con duración" /><StatusCard title="LCP / FCP / CLS / INP / TTFB" status={hasData ? "Instrumentado" : "Preparado"} detail="Métricas recogidas desde navegador" /></div></Panel><Panel icon={Eye} title="Qué estamos midiendo" subtitle="Sin contenido sensible"><Roadmap items={["Navegación y páginas vistas", "Usuarios y PYMEs activas", "Errores de producto", "Actividad IA agregada", "Rendimiento y latencia"]} /></Panel></div>{!hasData ? <div className="flex items-start gap-3 rounded-2xl border border-amber-300/10 bg-amber-300/[0.045] p-4"><AlertTriangle className="mt-0.5 h-5 w-5 text-amber-200/80" /><div><p className="text-sm font-medium">La interfaz ya está lista; falta activar la capa de datos</p><p className="mt-1 text-xs leading-5 text-white/45">La migración de platform_events debe ejecutarse en Supabase para que estos indicadores pasen de preparado a datos reales.</p></div></div> : null}</section>; }

function Growth({ metrics, loading }: { metrics: Metrics | null; loading: boolean }) { return <section className="grid gap-5 lg:grid-cols-2"><Panel icon={TrendingUp} title="Growth" subtitle="La base real que ya podemos observar."><div className="grid gap-3 sm:grid-cols-2"><Insight label="Usuarios" value={loading ? "—" : num(metrics?.users ?? 0)} detail="total actual" /><Insight label="Empresas" value={loading ? "—" : num(metrics?.businesses ?? 0)} detail="total actual" /><Insight label="Clientes" value={loading ? "—" : num(metrics?.customers ?? 0)} detail="registros actuales" /><Insight label="Cotizaciones" value={loading ? "—" : num(metrics?.quotes ?? 0)} detail="actividad comercial" /></div></Panel><Panel icon={Target} title="Funnel pendiente" subtitle="Instrumentación recomendada"><Roadmap items={["Visita → registro", "Registro → onboarding completado", "Onboarding → primera acción", "Primera acción → uso recurrente", "Trial → conversión"]} /></Panel></section>; }
function ProductHealth({ metrics }: { metrics: Metrics | null }) { return <section className="grid gap-5 lg:grid-cols-2"><Panel icon={Activity} title="Product Health" subtitle="Sin score ficticio."><div className="grid gap-3 sm:grid-cols-2"><StatusCard title="Base de datos" status="Con datos" detail={`${num(metrics?.transactions ?? 0)} transacciones observables`} /><StatusCard title="IA" status="Con datos" detail={`${num(metrics?.ai_messages ?? 0)} mensajes observables`} /><StatusCard title="Errores producción" status="Pendiente" detail="Ingestión centralizada pendiente" warn /><StatusCard title="Performance" status="Instrumentado" detail="Web Vitals preparado para persistencia" /></div></Panel><Panel icon={Clock3} title="Command Center técnico" subtitle="Siguiente capa"><Roadmap items={["Errores por versión", "Latencia de APIs", "Estado de deployments", "Web Vitals y disponibilidad", "Alertas automáticas"]} /></Panel></section>; }
function IA({ metrics, loading }: { metrics: Metrics | null; loading: boolean }) { const c=metrics?.ai_conversations??0; const m=metrics?.ai_messages??0; return <section className="grid gap-5 lg:grid-cols-2"><Panel icon={Bot} title="Nüva IA" subtitle="Uso agregado."><div className="grid gap-3 sm:grid-cols-3"><Insight label="Conversaciones" value={loading?"—":num(c)} detail="totales" /><Insight label="Mensajes" value={loading?"—":num(m)} detail="totales" /><Insight label="Profundidad" value={loading?"—":(c?`${(m/c).toFixed(1)}x`:"0")} detail="mensajes / conversación" /></div></Panel><Panel icon={Sparkles} title="Próxima instrumentación" subtitle="Medir valor real"><Roadmap items={["IA por empresa y módulo", "Errores y latencia", "Tokens / coste", "Adopción recurrente", "Funciones IA con mayor retención"]} /></Panel></section>; }
function Economia({ metrics, loading, net }: { metrics: Metrics | null; loading: boolean; net: number }) { return <section className="grid gap-5 lg:grid-cols-2"><Panel icon={CircleDollarSign} title="Economía de Nüva One" subtitle="Ingresos y costos propios de la plataforma; nunca las finanzas de las PYMEs."><div className="grid gap-3 sm:grid-cols-3"><Insight label="Ingresos de Nüva" value={loading?"—":clp.format(metrics?.income??0)} detail="suscripciones pagadas a Nüva One" /><Insight label="Costos de plataforma" value={loading?"—":clp.format(metrics?.expenses??0)} detail="costos registrados por el owner" /><Insight label="Neto de plataforma" value={loading?"—":clp.format(net)} detail="ingresos de Nüva − costos propios" /></div></Panel><Panel icon={Target} title="Monetización" subtitle="Métricas de negocio de Nüva One."><StatusCard title="MRR / ARR" status="En evolución" detail="Basado en suscripciones pagadas; falta consolidar el histórico mensual." /><StatusCard title="Trial → pago" status="Pendiente" detail="Requiere lifecycle events de conversión." /></Panel></section>; }
function MetricCard({ label, value, Icon, loading }: { label:string; value:number; Icon:typeof Users; loading:boolean }) { return <div className="rounded-2xl border border-white/9 bg-white/[0.035] p-4 shadow-xl shadow-black/10 transition hover:bg-white/[0.055]"><div className="flex items-center justify-between"><span className="text-xs text-white/45">{label}</span><Icon className="h-4 w-4 text-cyan-200/60" /></div><div className="mt-3 text-2xl font-semibold tracking-tight">{loading?"—":num(value)}</div></div>; }
function Panel({ icon:Icon, title, subtitle, children }: { icon:typeof Users; title:string; subtitle:string; children:React.ReactNode }) { return <div className="rounded-[26px] border border-white/9 bg-white/[0.035] p-5 shadow-2xl shadow-black/20 backdrop-blur-xl sm:p-6"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-cyan-200/70" /><h2 className="text-base font-semibold">{title}</h2></div><p className="mt-1 text-xs text-white/35">{subtitle}</p><div className="mt-5">{children}</div></div>; }
function Insight({ label, value, detail }: { label:string; value:string|number; detail:string }) { return <div className="rounded-2xl border border-white/7 bg-black/15 p-4"><div className="text-xs text-white/40">{label}</div><div className="mt-2 text-xl font-semibold">{typeof value === "number" ? value.toFixed(1) : value}</div><div className="mt-1 text-[11px] text-white/30">{detail}</div></div>; }
function Status({ label, ok }: { label:string; ok:boolean }) { return <div className="flex items-center gap-3 border-b border-white/7 py-3 last:border-0"><span className={`h-2 w-2 rounded-full ${ok?"bg-emerald-300":"bg-amber-300"}`} /><span className="text-sm text-white/65">{label}</span><span className="ml-auto text-xs text-white/35">{ok?"Activo":"Pendiente"}</span></div>; }
function StatusCard({ title, status, detail, warn=false }: { title:string; status:string; detail:string; warn?:boolean }) { return <div className="mb-3 rounded-2xl border border-white/7 bg-black/10 p-4 last:mb-0"><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">{title}</span><span className={`text-[11px] ${warn?"text-amber-200/80":"text-emerald-200/80"}`}>{status}</span></div><p className="mt-1 text-xs text-white/35">{detail}</p></div>; }
function Roadmap({ items }: { items:string[] }) { return <div className="space-y-2">{items.map((item,index)=><div key={item} className="flex items-center gap-3 rounded-xl border border-white/6 bg-black/10 px-3 py-2.5"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-white/7 text-[10px] text-white/45">{index+1}</span><span className="text-xs text-white/55">{item}</span></div>)}</div>; }
