import { Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, Sparkles } from "lucide-react";
import { useEffect, useRef, useState, type CSSProperties } from "react";
import { PublicAiChatWidget } from "@/components/public-ai-chat-widget";
import { EditorialLowerSections } from "@/components/editorial-home-experience-sections";
import { SceneArt } from "@/components/editorial-home-experience-scenes";
import { EDITORIAL_CHAPTERS, clamp, getChapterState } from "@/editorial-home-experience-engine";
function useProgress(ref:{current:HTMLElement|null}){const[progress,setProgress]=useState(0);useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const element=ref.current;if(!element)return;const range=Math.max(element.offsetHeight-window.innerHeight,1);setProgress(clamp(-element.getBoundingClientRect().top/range))})};update();window.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);return()=>{cancelAnimationFrame(frame);window.removeEventListener("scroll",update);window.removeEventListener("resize",update)}},[ref]);return progress}
export function EditorialHomeExperienceV2(){const storyRef=useRef<HTMLElement|null>(null);const progress=useProgress(storyRef);const[reducedMotion,setReducedMotion]=useState(false);const[direction,setDirection]=useState<"forward"|"backward">("forward");const previousProgress=useRef(0);const state=getChapterState(progress,reducedMotion);const active=state.activeChapter;const chapter=EDITORIAL_CHAPTERS[active];const previous=EDITORIAL_CHAPTERS[Math.max(0,active-1)];const next=EDITORIAL_CHAPTERS[Math.min(EDITORIAL_CHAPTERS.length-1,active+1)];const isBackward=direction==="backward"&&active>0;const outgoing=isBackward?previous:chapter;const incoming=isBackward?chapter:next;const transition=state.transitionProgress;
useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");const sync=()=>setReducedMotion(media.matches);sync();media.addEventListener?.("change",sync);return()=>media.removeEventListener?.("change",sync)},[]);
useEffect(()=>{if(progress>previousProgress.current+.0005)setDirection("forward");if(progress<previousProgress.current-.0005)setDirection("backward");previousProgress.current=progress},[progress]);
const go=(index:number)=>{const element=storyRef.current;if(!element)return;const range=Math.max(element.offsetHeight-window.innerHeight,1);const target=index===EDITORIAL_CHAPTERS.length-1?0.998:Math.min(0.998,index/EDITORIAL_CHAPTERS.length+0.02);window.scrollTo({top:window.scrollY+element.getBoundingClientRect().top+range*target,behavior:reducedMotion?"auto":"smooth"})};
return <div className="editorial-home"><header className="editorial-nav"><Link to="/" className="editorial-brand">Nüva One<span>.</span></Link><nav aria-label="Navegación de experiencia"><button onClick={()=>go(1)}>Producto</button><button onClick={()=>go(8)}>Inteligencia</button><Link to="/pricing">Precios</Link><a href="#editorial-faq">FAQ</a></nav><div className="editorial-nav__actions"><Link to="/demo" className="editorial-demo"><Sparkles size={14}/>Demo</Link><Link to="/auth" search={{mode:"signup"}} className="editorial-cta">Empezar gratis <ArrowRight size={14}/></Link></div></header><main><section ref={storyRef} className="editorial-story" aria-label="Nüva One, una historia de negocio"><div className="editorial-story__sticky"><div className="editorial-story__progress-readout" aria-live="off"><span>PROGRESO</span><strong>{Math.round(progress*100)}%</strong><i><b style={{transform:`scaleX(${progress})`}}/></i></div><div className={`editorial-story__background editorial-story__background--${chapter.visual}`} style={{"--scene-progress":transition} as CSSProperties}/><div className="editorial-story__art-wrap" style={{opacity:1-transition,filter:`blur(${(1-transition)*2}px)`}}><SceneArt kind={outgoing.visual} progress={isBackward?.5:state.localProgress} reducedMotion={reducedMotion}/></div><div className="editorial-story__art-wrap" style={{opacity:transition,filter:`blur(${(1-transition)*2}px)`}}><SceneArt kind={incoming.visual} progress={isBackward?state.localProgress:0} reducedMotion={reducedMotion}/></div><div className="editorial-story__veil"/><div className="editorial-story__topline"><span>EXPERIENCIA / NÜVA ONE</span><span>{String(active+1).padStart(2,"0")} — {String(EDITORIAL_CHAPTERS.length).padStart(2,"0")}</span></div><div key={chapter.id} className="editorial-story__copy"><span className="editorial-kicker">{chapter.kicker}</span><h1>{chapter.title}</h1><p>{chapter.text}</p><span className="editorial-scroll-note"><ArrowDown size={14}/>Desplaza para continuar</span></div><div key={`metric-${chapter.id}`} className="editorial-story__metric"><span>{chapter.metric}</span><small>SEÑAL DEL NEGOCIO</small></div><aside className="editorial-chapters" aria-label="Capítulos">{EDITORIAL_CHAPTERS.map((item,index)=><button key={item.id} className={index===active?"is-active":""} onClick={()=>go(index)} aria-label={`Ir a ${item.label}`} aria-current={index===active?"step":undefined}><i/><span>{item.label}</span></button>)}</aside><div className="editorial-progress"><span style={{transform:`scaleX(${progress})`}}/></div></div></section><EditorialLowerSections/></main><PublicAiChatWidget/></div>}
