import { useMemo, useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, Calculator, CircleDollarSign, Clock3, ExternalLink, Info, Landmark, Receipt, ShieldCheck, Sparkles, TrendingUp, WalletCards } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useBizList, fmtCLP } from "@/lib/biz-data";
import { buildFinanceGuardian } from "@/lib/nuva-finance-guardian";
import { buildCashflowForecast } from "@/lib/nuva-cashflow-forecast";

type Tab = "treasury" | "receivables" | "posting" | "intelligence" | "tools";
const money = (v: unknown) => fmtCLP(Math.round(Number(v || 0)));
const taxOf = (row: any) => Number(row?.tax ?? row?.iva_amount ?? row?.vat_amount ?? row?.iva ?? 0);

const TAB_INFO: Record<Tab, { title: string; description: string }> = {
  treasury: { title: "Tesorería", description: "Muestra entradas, salidas, obligaciones y flujo neto para entender la liquidez disponible." },
  receivables: { title: "Cuentas por cobrar", description: "Identifica dinero pendiente de clientes, fechas de vencimiento y cartera vencida." },
  posting: { title: "Pendientes contables", description: "Separa movimientos operativos que todavía requieren clasificación o revisión contable." },
  intelligence: { title: "Inteligencia financiera", description: "Combina señales de riesgo, IVA estimado y proyección de caja para apoyar decisiones." },
  tools: { title: "Herramientas", description: "Accesos a cálculos y espacios especializados para precios, costos, contabilidad y tributación." },
};

export function FinanceAdvancedTools() {
  const [tab, setTab] = useState<Tab>("treasury");
  const [toolInfo, setToolInfo] = useState<string | null>(null);
  const { data: treasury = [] } = useBizList<any>("v_financial_treasury_daily", { order: "flow_date", ascending: true });
  const { data: queue = [] } = useBizList<any>("financial_posting_queue", { order: "created_at", ascending: false });
  const { data: sales = [] } = useBizList<any>("sales", { order: "sale_date", ascending: false });
  const { data: purchases = [] } = useBizList<any>("purchases", { order: "purchase_date", ascending: false });
  const { data: taxPayments = [] } = useBizList<any>("tax_payments", { order: "due_date", ascending: true });
  const { data: transactions = [] } = useBizList<any>("transactions", { order: "tx_date", ascending: false });

  const receivables = useMemo(() => sales.filter((s: any) => s.is_credit && s.status !== "cancelled").map((s: any) => ({ ...s, pending: Math.max(0, Number(s.total || 0) - Number(s.paid_amount || 0)) })).filter((s: any) => s.pending > 0).sort((a: any, b: any) => b.pending - a.pending), [sales]);
  const payables = useMemo(() => purchases.filter((p: any) => p.status !== "cancelled").map((p: any) => ({ ...p, pending: Math.max(0, Number(p.total || 0) - Number(p.paid_amount || 0)) })).filter((p: any) => p.pending > 0).sort((a: any, b: any) => b.pending - a.pending), [purchases]);
  const treasurySummary = useMemo(() => { const rows = treasury as any[]; const inflow = rows.reduce((s, x) => s + Number(x.inflow || 0), 0); const outflow = rows.reduce((s, x) => s + Number(x.outflow || 0), 0); return { inflow, outflow, net: inflow - outflow }; }, [treasury]);
  const queueSummary = useMemo(() => { const pending = queue.filter((x: any) => ["pending", "blocked"].includes(x.status)); return { count: pending.length, amount: pending.reduce((s: number, x: any) => s + Number(x.gross_amount || 0), 0), blocked: pending.filter((x: any) => x.status === "blocked").length }; }, [queue]);
  const receivableSummary = useMemo(() => ({ amount: receivables.reduce((s: number, x: any) => s + x.pending, 0), overdue: receivables.filter((x: any) => x.due_date && new Date(x.due_date) < new Date()).reduce((s: number, x: any) => s + x.pending, 0) }), [receivables]);
  const taxDue = useMemo(() => taxPayments.filter((x: any) => ["planned", "due", "overdue", "partial"].includes(x.status)).reduce((s: number, x: any) => s + Math.max(0, Number(x.amount || 0) - Number(x.paid_amount || 0)), 0), [taxPayments]);
  const currentOperationalCash = useMemo(() => transactions.reduce((s: number, x: any) => s + (x.type === "income" ? Number(x.amount || 0) : -Number(x.amount || 0)), 0), [transactions]);
  const guardian = useMemo(() => buildFinanceGuardian({ sales: sales.filter((s: any) => s.status !== "cancelled").map((s: any) => ({ total: Number(s.total || 0), tax: taxOf(s), date: String(s.sale_date || "") })), purchases: purchases.filter((p: any) => p.status !== "cancelled").map((p: any) => ({ total: Number(p.total || 0), tax: taxOf(p), date: String(p.purchase_date || "") })), receivables: receivables.map((s: any) => ({ amount: s.pending, dueDate: String(s.due_date || "2099-12-31"), paid: false })), payables: payables.map((p: any) => ({ amount: p.pending, dueDate: String(p.due_date || "2099-12-31"), paid: false })), cash: currentOperationalCash }), [sales, purchases, receivables, payables, currentOperationalCash]);
  const forecast = useMemo(() => buildCashflowForecast({ currentBalance: currentOperationalCash, items: [...receivables.map((s: any) => ({ amount: s.pending, dueDate: String(s.due_date || ""), kind: "inflow" as const, status: "open" as const })), ...payables.map((p: any) => ({ amount: p.pending, dueDate: String(p.due_date || ""), kind: "outflow" as const, status: "open" as const })), ...taxPayments.filter((x: any) => ["planned", "due", "overdue", "partial"].includes(x.status)).map((x: any) => ({ amount: Math.max(0, Number(x.amount || 0) - Number(x.paid_amount || 0)), dueDate: String(x.due_date || ""), kind: "outflow" as const, status: "open" as const }))] }), [currentOperationalCash, receivables, payables, taxPayments]);
  const tabs: [Tab, string, any][] = [["treasury", "Tesorería", WalletCards], ["receivables", "Por cobrar", CircleDollarSign], ["posting", "Pendientes contables", ShieldCheck], ["intelligence", "Inteligencia", Sparkles], ["tools", "Herramientas", Calculator]];

  return <Card className="overflow-hidden">
    <div className="border-b p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><Landmark className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold">Control financiero avanzado</h2><Info className="h-4 w-4 text-muted-foreground" aria-label="Información sobre control financiero avanzado" /></div><p className="mt-1 text-sm text-muted-foreground">Tesorería, cartera, clasificación contable, riesgo de caja y herramientas de decisión.</p></div><div className="flex gap-2 overflow-x-auto">{tabs.map(([key, label, Icon]) => <button key={key} type="button" onClick={() => setTab(key)} title={TAB_INFO[key].description} aria-label={`${label}: ${TAB_INFO[key].description}`} className={`flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium ${tab === key ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}><Icon className="h-4 w-4" />{label}<Info className="h-3.5 w-3.5 opacity-70" aria-hidden="true" /></button>)}</div></div><div className="mt-4 rounded-xl border bg-muted/30 p-3 text-xs text-muted-foreground"><span className="font-semibold text-foreground">{TAB_INFO[tab].title}:</span> {TAB_INFO[tab].description}</div></div>
    {tab === "treasury" && <div className="space-y-5 p-5"><div className="grid gap-3 md:grid-cols-3"><Metric label="Entradas registradas" value={money(treasurySummary.inflow)} icon={ArrowUpRight} /><Metric label="Salidas + obligaciones" value={money(treasurySummary.outflow)} icon={ArrowDownRight} /><Metric label="Flujo neto" value={money(treasurySummary.net)} icon={TrendingUp} good={treasurySummary.net >= 0} /></div>{taxDue > 0 && <div className="flex items-start gap-3 rounded-xl border p-4 text-sm"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" /><div><b>{money(taxDue)}</b> de obligaciones tributarias están consideradas en la vista de tesorería.</div></div>}{!treasury.length ? <Empty text="Todavía no hay movimientos de tesorería registrados." /> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">Fecha</th><th className="p-2 text-right">Entradas</th><th className="p-2 text-right">Salidas</th><th className="p-2 text-right">Neto</th></tr></thead><tbody>{treasury.slice(-12).reverse().map((x: any) => <tr key={`${x.flow_date}-${x.business_id}`} className="border-b last:border-0"><td className="p-2">{new Date(x.flow_date).toLocaleDateString("es-CL")}</td><td className="p-2 text-right">{money(x.inflow)}</td><td className="p-2 text-right">{money(x.outflow)}</td><td className={`p-2 text-right font-medium ${Number(x.net_flow) < 0 ? "text-destructive" : ""}`}>{money(x.net_flow)}</td></tr>)}</tbody></table></div>}</div>}
    {tab === "receivables" && <div className="space-y-5 p-5"><div className="grid gap-3 md:grid-cols-2"><Metric label="Cartera pendiente" value={money(receivableSummary.amount)} icon={CircleDollarSign} /><Metric label="Vencido" value={money(receivableSummary.overdue)} icon={Clock3} good={receivableSummary.overdue === 0} /></div>{!receivables.length ? <Empty text="No hay cuentas por cobrar pendientes." /> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">Cliente</th><th className="p-2">Vencimiento</th><th className="p-2 text-right">Pendiente</th><th className="p-2">Estado</th></tr></thead><tbody>{receivables.slice(0, 20).map((x: any) => { const overdue = x.due_date && new Date(x.due_date) < new Date(); return <tr key={x.id} className="border-b last:border-0"><td className="p-2 font-medium">{x.customer_name || x.customer || "Cliente"}</td><td className="p-2">{x.due_date ? new Date(x.due_date).toLocaleDateString("es-CL") : "Sin vencimiento"}</td><td className="p-2 text-right font-medium">{money(x.pending)}</td><td className="p-2"><Badge variant={overdue ? "destructive" : "outline"}>{overdue ? "Vencido" : "Pendiente"}</Badge></td></tr>; })}</tbody></table></div>}</div>}
    {tab === "posting" && <div className="space-y-5 p-5"><div className="grid gap-3 md:grid-cols-3"><Metric label="Pendientes" value={String(queueSummary.count)} icon={Clock3} good={queueSummary.count === 0} /><Metric label="Monto por clasificar" value={money(queueSummary.amount)} icon={Receipt} /><Metric label="Bloqueados" value={String(queueSummary.blocked)} icon={ShieldCheck} good={queueSummary.blocked === 0} /></div><div className="rounded-xl border p-4 text-sm text-muted-foreground">La cola separa el registro operativo de la contabilización: ningún movimiento se publica automáticamente cuando falta clasificación contable o tributaria.</div>{!queue.length ? <Empty text="La cola contable está limpia." /> : <div className="space-y-2">{queue.slice(0, 12).map((x: any) => <div key={x.id} className="flex flex-col gap-2 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Badge variant={x.status === "blocked" ? "destructive" : "outline"}>{x.status}</Badge><span className="font-medium capitalize">{x.source_type === "sale" ? "Venta" : "Compra"}</span></div><p className="mt-1 text-xs text-muted-foreground">{x.reason || "Revisión contable pendiente"}</p></div><span className="font-semibold">{money(x.gross_amount)}</span></div>)}</div>}</div>}
    {tab === "intelligence" && <div className="space-y-5 p-5"><div className="grid gap-3 md:grid-cols-3"><Metric label="IVA estimado" value={money(guardian.estimatedVat)} icon={Receipt} /><Metric label="Caja proyectada 30 días" value={money(forecast.projectedBalance30d)} icon={TrendingUp} good={forecast.risk !== "high"} /><Metric label="Mínimo proyectado" value={money(forecast.minimumProjectedBalance30d)} icon={ShieldCheck} good={forecast.minimumProjectedBalance30d >= 0} /></div><div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Nüva Finance Guardian</h3><p className="text-xs text-muted-foreground">Señales explicables de IVA, cartera y liquidez.</p></div><Badge variant={guardian.signals.some(s => s.severity === "critical") ? "destructive" : "outline"}>{guardian.signals.length ? `${guardian.signals.length} señales` : "Sin señales"}</Badge></div><div className="mt-4 space-y-3">{guardian.signals.length ? guardian.signals.slice(0, 5).map(s => <div key={s.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><span className="font-medium">{s.title}</span><Badge variant={s.severity === "critical" ? "destructive" : "outline"}>{s.severity}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{s.detail}</p></div>) : <Empty text="No se detectaron señales prioritarias con los datos disponibles." />}</div></Card><Card className="p-5"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-primary" /><div><h3 className="font-semibold">Pronóstico de caja</h3><p className="text-xs text-muted-foreground">Escenario automático a 30 días con cartera, pagos y obligaciones conocidas.</p></div></div><div className="mt-4 rounded-xl border p-4"><p className="text-xs text-muted-foreground">Riesgo</p><p className="mt-1 text-2xl font-bold capitalize">{forecast.risk}</p><p className="mt-2 text-sm">Caja operacional actual: <b>{money(forecast.currentBalance)}</b></p><p className="text-sm">Caja proyectada: <b>{money(forecast.projectedBalance30d)}</b></p>{forecast.runwayDays !== null && <p className="text-sm">Runway estimado: <b>{forecast.runwayDays} días</b></p>}</div>{forecast.actions.length > 0 && <div className="mt-4 space-y-2">{forecast.actions.map(action => <div key={action} className="rounded-lg border p-3 text-sm">{action}</div>)}</div>}</Card></div></div>}
    {tab === "tools" && <div className="grid gap-4 p-5 md:grid-cols-2"><Tool title="Calculadora inteligente de precios" description="Piso de precio, margen, punto de equilibrio y recomendación conectada al contexto de productos." info="Calcula un precio recomendado considerando costos, margen y punto de equilibrio." href="/pricing-calculator" icon={Calculator} infoKey="pricing" toolInfo={toolInfo} setToolInfo={setToolInfo} /><Tool title="Control de costos" description="Costos fijos, variables, vencimientos, IVA, centros de costo y análisis por categoría." info="Permite revisar el origen y comportamiento de los costos para detectar fugas y oportunidades de eficiencia." href="/purchases" icon={Receipt} infoKey="costs" toolInfo={toolInfo} setToolInfo={setToolInfo} /><Tool title="Contabilidad profesional" description="Plan de cuentas, diario, mayor, estados financieros, IVA, documentos y cierre." info="Organiza y revisa la información contable, cuentas, movimientos y estados financieros." href="#contabilidad" icon={Landmark} infoKey="accounting" toolInfo={toolInfo} setToolInfo={setToolInfo} /><Tool title="Control tributario Chile" description="IVA, documentos de respaldo, pagos y controles de cierre." info="Centraliza controles tributarios relevantes para Chile y ayuda a identificar obligaciones y respaldos." href="#tributario" icon={ShieldCheck} infoKey="tax" toolInfo={toolInfo} setToolInfo={setToolInfo} /></div>}
  </Card>;
}

function Metric({ label, value, icon: Icon, good }: { label: string; value: string; icon: any; good?: boolean }) { return <Card className="p-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-primary/10 p-2"><Icon className="h-4 w-4 text-primary" /></div><div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className={`text-lg font-bold ${good === false ? "text-destructive" : ""}`}>{value}</p></div></div></Card>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">{text}</div>; }
function Tool({ title, description, info, href, icon: Icon, infoKey, toolInfo, setToolInfo }: { title: string; description: string; info: string; href: string; icon: any; infoKey: string; toolInfo: string | null; setToolInfo: (value: string | null) => void }) { const external = href.startsWith("http"); const open = toolInfo === infoKey; return <div className="rounded-xl border p-5"><div className="flex items-start gap-3"><div className="rounded-lg bg-primary/10 p-2"><Icon className="h-5 w-5 text-primary" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="font-semibold">{title}</h3><button type="button" onClick={() => setToolInfo(open ? null : infoKey)} title={`Información: ${title}`} aria-label={`Información sobre ${title}`} aria-expanded={open} className="rounded-full p-1 text-muted-foreground hover:bg-muted hover:text-foreground"><Info className="h-4 w-4" /></button></div><p className="mt-1 text-sm text-muted-foreground">{description}</p>{open && <div className="mt-3 rounded-lg border bg-muted/30 p-3 text-xs leading-5 text-muted-foreground"><p className="font-semibold text-foreground">¿Qué hace?</p><p className="mt-1">{info}</p><p className="mt-2 font-semibold text-foreground">¿Cuándo usarla?</p><p className="mt-1">Cuando necesites convertir los datos financieros registrados en una revisión o decisión concreta.</p></div>}{href.startsWith("#") ? <p className="mt-3 text-xs text-muted-foreground">Disponible en el espacio contable de esta misma página.</p> : <Button asChild variant="outline" size="sm" className="mt-3"><a href={href}>{external ? <ExternalLink className="mr-1.5 h-4 w-4" /> : null}Abrir herramienta</a></Button>}</div></div></div>; }
