import { useMemo, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { Boxes, ClipboardCheck, Download, History, PackagePlus, Pencil, Plus, Search, ShoppingCart, SlidersHorizontal, Sparkles, Trash2 } from "lucide-react";
import { PageHeader, EmptyState } from "@/components/page-utils";
import { ModuleGuard } from "@/components/module-guard";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { fmtCLP, useBizDelete, useBizInsert, useBizList, useBizUpdate } from "@/lib/biz-data";
import { downloadCsv } from "@/lib/export";
import { canWriteOperations, useActiveBusinessId, useMyRole } from "@/lib/use-business";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { NuvaInventoryIntelligence } from "@/components/nuva-inventory-intelligence";
import { InventoryActionCenter } from "@/components/inventory-action-center";
import { getInventoryMetrics, type InventoryStatus } from "@/lib/inventory-metrics";
import { adjustInventoryStock } from "@/lib/inventory-transactions";

type Product = {
  id: string;
  name: string | null;
  sku: string | null;
  stock: number | null;
  reserved_stock: number | null;
  in_transit_stock: number | null;
  blocked_stock: number | null;
  low_stock_threshold: number | null;
  reorder_point: number | null;
  max_stock: number | null;
  cost: number | null;
  price: number | null;
};
type View = "intelligence" | "stock" | "products" | "replenishment";
const views = [["intelligence", "Intelligence", "Entiende qué pasa y qué atender.", Sparkles], ["stock", "Stock", "Consulta disponibilidad y reposición.", Boxes], ["products", "Productos", "Administra catálogo y parámetros.", PackagePlus], ["replenishment", "Abastecimiento", "Convierte alertas en una compra accionable.", ShoppingCart]] as const;
const statusText: Record<InventoryStatus, string> = { out_of_stock: "Sin stock", critical: "Crítico", reorder: "Reponer", healthy: "Saludable" };

export function InventoryWorkspace() {
  const navigate = useNavigate(); const { data: role } = useMyRole(); const canWrite = canWriteOperations(role); const [businessId] = useActiveBusinessId();
  const { data, isLoading } = useBizList<Product>("products", { order: "created_at" }); const insert = useBizInsert("products"); const update = useBizUpdate("products"); const remove = useBizDelete("products");
  const products = data ?? []; const [view, setView] = useState<View>("intelligence"); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Product | null>(null); const [adjustOpen, setAdjustOpen] = useState(false); const [adjustProduct, setAdjustProduct] = useState<Product | null>(null);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? products.filter(p => `${p.name ?? ""} ${p.sku ?? ""}`.toLowerCase().includes(q)) : products; }, [products, query]);
  const metrics = products.map(p => getInventoryMetrics(p)); const available = metrics.reduce((s, m) => s + m.available, 0); const critical = metrics.filter(m => m.status === "out_of_stock" || m.status === "critical").length; const value = products.reduce((s, p) => s + Number(p.stock ?? 0) * Number(p.cost ?? 0), 0);
  const replenishment = useMemo(() => products.map(product => ({ product, metrics: getInventoryMetrics(product) })).filter(({ metrics: m }) => m.suggestedReplenishment > 0).sort((a, b) => b.metrics.suggestedReplenishment - a.metrics.suggestedReplenishment), [products]);
  const replenishmentUnits = replenishment.reduce((s, item) => s + item.metrics.suggestedReplenishment, 0); const replenishmentValue = replenishment.reduce((s, item) => s + item.metrics.suggestedReplenishment * Number(item.product.cost ?? 0), 0);
  const create = () => { setEditing(null); setOpen(true); }; const edit = (p: Product) => { setEditing(p); setOpen(true); }; const adjust = (p: Product) => { setAdjustProduct(p); setAdjustOpen(true); };
  async function save(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if (!canWrite || !businessId) return; const f = new FormData(e.currentTarget); const stock = Math.max(0, Number(f.get("stock") || 0)); const patch = { name: String(f.get("name") || "").trim(), sku: String(f.get("sku") || "").trim() || null, low_stock_threshold: Math.max(0, Number(f.get("minimum") || 0)), reorder_point: Math.max(0, Number(f.get("reorder") || 0)), max_stock: Math.max(0, Number(f.get("target") || 0)), cost: Math.max(0, Number(f.get("cost") || 0)), price: Math.max(0, Number(f.get("price") || 0)) }; if (!patch.name) return toast.error("Ingresa el nombre del producto."); try { if (editing) { await update.mutateAsync({ id: editing.id, patch }); const delta = stock - Number(editing.stock || 0); if (delta) await adjustInventoryStock(supabase, { productId: editing.id, delta, reason: "Ajuste desde ficha de producto", sourceType: "product_edit", sourceId: editing.id }); } else { const created = await insert.mutateAsync({ business_id: businessId, ...patch, stock: 0 }); if (stock) { const id = (created as { id: string }).id; await adjustInventoryStock(supabase, { productId: id, delta: stock, reason: "Stock inicial al crear producto", sourceType: "product_initial_stock", sourceId: id }); } } toast.success(editing ? "Producto actualizado" : "Producto creado"); setOpen(false); } catch (err: any) { toast.error(err?.message || "No se pudo guardar el producto."); } }
  async function doAdjust(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if (!adjustProduct || !canWrite) return; const f = new FormData(e.currentTarget); const delta = Number(f.get("delta")); const reason = String(f.get("reason") || "").trim(); if (!Number.isInteger(delta) || delta === 0) return toast.error("Usa un entero distinto de cero."); if (!reason) return toast.error("Indica el motivo."); try { await adjustInventoryStock(supabase, { productId: adjustProduct.id, delta, reason, sourceType: "manual_adjustment" }); toast.success("Stock ajustado y trazado"); setAdjustOpen(false); } catch (err: any) { toast.error(err?.message || "No se pudo ajustar el stock."); } }
  async function del(p: Product) { if (!canWrite || !window.confirm(`¿Eliminar ${p.name || "este producto"}?`)) return; try { await remove.mutateAsync(p.id); toast.success("Producto eliminado"); } catch { toast.error("No se pudo eliminar el producto"); } }
  function exportData() { downloadCsv("nuva-inventario.csv", products.map(p => { const m = getInventoryMetrics(p); return { SKU: p.sku || "", Producto: p.name || "", Stock: Number(p.stock || 0), Disponible: m.available, Proyectado: m.projected, Estado: statusText[m.status], Reposicion: m.suggestedReplenishment, Costo: Number(p.cost || 0), Precio: Number(p.price || 0), ValorCosto: Number(p.stock || 0) * Number(p.cost || 0) }; })); }
  function exportReplenishment() { downloadCsv("nuva-abastecimiento.csv", replenishment.map(({ product: p, metrics: m }) => ({ SKU: p.sku || "", Producto: p.name || "", Proyectado: m.projected, Reposicion: m.suggestedReplenishment, CostoUnitario: Number(p.cost || 0), InversionEstimada: m.suggestedReplenishment * Number(p.cost || 0), Estado: statusText[m.status] }))); }
  return <ModuleGuard module="inventory"><div className="space-y-5"><PageHeader title="Inventario" description="Entiende, controla y opera tu inventario sin mezclar decisiones con tareas operativas." actions={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={exportData} disabled={!products.length}><Download className="mr-2 h-4 w-4" />Exportar</Button>{canWrite && <Button onClick={create}><Plus className="mr-2 h-4 w-4" />Nuevo producto</Button>}</div>} />
    <Card className="overflow-hidden"><div className="grid md:grid-cols-3 lg:grid-cols-6">{views.map(([id, label, desc, Icon]) => <button key={id} type="button" onClick={() => setView(id)} className={`min-h-[82px] border-b p-4 text-left lg:border-b-0 lg:border-r ${view === id ? "bg-primary/[0.06] text-primary" : "hover:bg-muted/50"}`}><div className="flex items-center gap-2 text-sm font-semibold"><Icon className="h-4 w-4" />{label}</div><p className="mt-1 text-xs text-muted-foreground">{desc}</p></button>)}<button type="button" onClick={() => navigate({ to: "/inventario-operaciones" })} className="min-h-[82px] border-b p-4 text-left hover:bg-muted/50 lg:border-b-0 lg:border-r"><div className="flex items-center gap-2 text-sm font-semibold"><History className="h-4 w-4" />Movimientos</div><p className="mt-1 text-xs text-muted-foreground">Entradas, salidas, devoluciones y ajustes.</p></button><button type="button" onClick={() => navigate({ to: "/inventario-conteo" })} className="min-h-[82px] border-b p-4 text-left hover:bg-muted/50 lg:border-b-0 lg:border-r"><div className="flex items-center gap-2 text-sm font-semibold"><ClipboardCheck className="h-4 w-4" />Conteo</div><p className="mt-1 text-xs text-muted-foreground">Físico vs. sistema y correcciones.</p></button></div></Card>
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Productos" value={String(products.length)} /><Stat label="Disponibles" value={String(available)} /><Stat label="Atención" value={String(critical)} danger={critical > 0} /></div>
    {view === "intelligence" && <><NuvaInventoryIntelligence products={products} /><InventoryActionCenter products={products} canWrite={canWrite} /></>}
    {view === "stock" && <StockView products={filtered} loading={isLoading} value={value} query={query} onQuery={setQuery} onAdjust={adjust} />}
    {view === "products" && <ProductsView products={filtered} loading={isLoading} query={query} onQuery={setQuery} onCreate={create} onEdit={edit} onAdjust={adjust} onDelete={del} canWrite={canWrite} />}
    {view === "replenishment" && <ReplenishmentView items={replenishment} units={replenishmentUnits} value={replenishmentValue} onExport={exportReplenishment} onPurchase={() => navigate({ to: "/purchases" })} onAdjust={adjust} />}
    <div className="rounded-xl border border-dashed bg-muted/20 p-4 text-sm text-muted-foreground"><strong className="text-foreground">Flujo:</strong> Intelligence = decidir · Stock = consultar · Movimientos = operar · Conteo = verificar · Productos = administrar · Abastecimiento = preparar compra.<Button variant="link" className="h-auto px-1" onClick={() => navigate({ to: "/purchases" })}>Ir a Compras</Button></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "Editar producto" : "Nuevo producto"}</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-4"><Field label="Producto"><Input name="name" defaultValue={editing?.name ?? ""} required /></Field><div className="grid grid-cols-2 gap-3"><Field label="SKU"><Input name="sku" defaultValue={editing?.sku ?? ""} /></Field><Field label="Stock"><Input name="stock" type="number" min="0" defaultValue={editing?.stock ?? 0} /></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Mínimo"><Input name="minimum" type="number" min="0" defaultValue={editing?.low_stock_threshold ?? 0} /></Field><Field label="Reposición"><Input name="reorder" type="number" min="0" defaultValue={editing?.reorder_point ?? 0} /></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Costo"><Input name="cost" type="number" min="0" defaultValue={editing?.cost ?? 0} /></Field><Field label="Precio"><Input name="price" type="number" min="0" defaultValue={editing?.price ?? 0} /></Field></div><Field label="Stock objetivo"><Input name="target" type="number" min="0" defaultValue={editing?.max_stock ?? 0} /></Field><Button className="w-full" type="submit" disabled={!canWrite}>{editing ? "Guardar cambios" : "Crear producto"}</Button></form></DialogContent></Dialog>
    <Dialog open={adjustOpen} onOpenChange={setAdjustOpen}><DialogContent><DialogHeader><DialogTitle>Ajustar stock · {adjustProduct?.name || "Producto"}</DialogTitle></DialogHeader><form onSubmit={doAdjust} className="space-y-4"><p className="text-sm text-muted-foreground">Positivo = entrada · negativo = salida. El movimiento queda trazado.</p><Field label="Cantidad (+ / -)"><Input name="delta" type="number" step="1" required /></Field><Field label="Motivo"><Input name="reason" placeholder="Recepción, merma, corrección…" required /></Field><Button className="w-full" type="submit" disabled={!canWrite}>Registrar ajuste</Button></form></DialogContent></Dialog>
  </div></ModuleGuard>;
}
function Stat({ label, value, danger }: { label: string; value: string; danger?: boolean }) { return <Card className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 text-2xl font-bold tabular-nums ${danger ? "text-destructive" : ""}`}>{value}</p></Card>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label>{label}</Label><div className="mt-1.5">{children}</div></div>; }
function SearchBox({ value, onQuery }: { value: string; onQuery: (v: string) => void }) { return <div className="relative w-full sm:max-w-sm"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={value} onChange={e => onQuery(e.target.value)} placeholder="Buscar producto o SKU…" className="pl-9" aria-label="Buscar producto o SKU" /></div>; }
function StockView({ products, loading, value, query, onQuery, onAdjust }: { products: Product[]; loading: boolean; value: number; query: string; onQuery: (v: string) => void; onAdjust: (p: Product) => void }) { return <Card><div className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Stock y disponibilidad</h2><p className="mt-1 text-sm text-muted-foreground">Disponible y proyectado. Valor a costo: {fmtCLP(value)}.</p></div><SearchBox value={query} onQuery={onQuery} /></div>{loading ? <Skeleton className="mt-4 h-12 w-full" /> : products.length ? <div className="mt-4 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead>Disponible</TableHead><TableHead>Proyectado</TableHead><TableHead>Reposición</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Acción</TableHead></TableRow></TableHeader><TableBody>{products.map(p => { const m = getInventoryMetrics(p); return <TableRow key={p.id}><TableCell className="font-medium">{p.name || "Sin nombre"}<div className="text-xs text-muted-foreground">{p.sku || "Sin SKU"}</div></TableCell><TableCell className="font-semibold">{m.available}</TableCell><TableCell>{m.projected}</TableCell><TableCell>{m.suggestedReplenishment}</TableCell><TableCell><Badge variant={m.status === "out_of_stock" || m.status === "critical" ? "destructive" : "outline"}>{statusText[m.status]}</Badge></TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => onAdjust(p)}><SlidersHorizontal className="mr-1 h-3.5 w-3.5" />Ajustar</Button></TableCell></TableRow>; })}</TableBody></Table></div> : <EmptyState title={query ? "Sin coincidencias" : "Sin productos"} description={query ? "Prueba otro nombre o SKU." : "Agrega tu primer producto para comenzar."} />}</div></Card>; }
function ProductsView({ products, loading, query, onQuery, onCreate, onEdit, onAdjust, onDelete, canWrite }: { products: Product[]; loading: boolean; query: string; onQuery: (v: string) => void; onCreate: () => void; onEdit: (p: Product) => void; onAdjust: (p: Product) => void; onDelete: (p: Product) => void; canWrite: boolean }) { return <Card><div className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Productos</h2><p className="mt-1 text-sm text-muted-foreground">Catálogo, SKU, parámetros de stock, costo y precio.</p></div><div className="flex flex-wrap gap-2"><SearchBox value={query} onQuery={onQuery} />{canWrite && <Button size="sm" onClick={onCreate}><Plus className="mr-1 h-4 w-4" />Nuevo producto</Button>}</div></div>{loading ? <Skeleton className="mt-4 h-12 w-full" /> : products.length ? <div className="mt-4 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead>SKU</TableHead><TableHead>Stock</TableHead><TableHead>Mínimo</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{products.map(p => { const m = getInventoryMetrics(p); return <TableRow key={p.id}><TableCell className="font-medium">{p.name || "Sin nombre"}</TableCell><TableCell>{p.sku || "—"}</TableCell><TableCell>{Number(p.stock || 0)}</TableCell><TableCell>{Number(p.low_stock_threshold || 0)}</TableCell><TableCell><Badge variant={m.status === "out_of_stock" || m.status === "critical" ? "destructive" : "outline"}>{statusText[m.status]}</Badge></TableCell><TableCell className="text-right"><div className="flex justify-end gap-1">{canWrite && <><Button size="icon" variant="ghost" onClick={() => onEdit(p)} aria-label={`Editar ${p.name || "producto"}`}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => onAdjust(p)} aria-label={`Ajustar ${p.name || "producto"}`}><SlidersHorizontal className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => onDelete(p)} aria-label={`Eliminar ${p.name || "producto"}`}><Trash2 className="h-4 w-4" /></Button></>}</div></TableCell></TableRow>; })}</TableBody></Table></div> : <EmptyState title={query ? "Sin coincidencias" : "Sin productos"} description={query ? "Prueba otro nombre o SKU." : "Agrega tu primer producto para comenzar."} />}</div></Card>; }
function ReplenishmentView({ items, units, value, onExport, onPurchase, onAdjust }: { items: Array<{ product: Product; metrics: ReturnType<typeof getInventoryMetrics> }>; units: number; value: number; onExport: () => void; onPurchase: () => void; onAdjust: (p: Product) => void }) { return <Card><div className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Abastecimiento</h2><p className="mt-1 text-sm text-muted-foreground">Productos cuyo stock proyectado requiere reposición según sus parámetros.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={onExport} disabled={!items.length}><Download className="mr-2 h-4 w-4" />Exportar lista</Button><Button onClick={onPurchase} disabled={!items.length}><ShoppingCart className="mr-2 h-4 w-4" />Preparar compra</Button></div></div>{items.length ? <><div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat label="Productos a reponer" value={String(items.length)} danger /><Stat label="Unidades sugeridas" value={String(units)} /><Stat label="Inversión estimada" value={fmtCLP(value)} /></div><div className="mt-5 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead>Proyectado</TableHead><TableHead>Comprar</TableHead><TableHead>Costo estimado</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Acción</TableHead></TableRow></TableHeader><TableBody>{items.map(({ product: p, metrics: m }) => <TableRow key={p.id}><TableCell className="font-medium">{p.name || "Sin nombre"}<div className="text-xs text-muted-foreground">{p.sku || "Sin SKU"}</div></TableCell><TableCell>{m.projected}</TableCell><TableCell className="font-semibold">{m.suggestedReplenishment}</TableCell><TableCell>{fmtCLP(m.suggestedReplenishment * Number(p.cost ?? 0))}</TableCell><TableCell><Badge variant={m.status === "out_of_stock" || m.status === "critical" ? "destructive" : "outline"}>{statusText[m.status]}</Badge></TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => onAdjust(p)}>Ajustar</Button></TableCell></TableRow>)}</TableBody></Table></div></> : <EmptyState title="Sin reposiciones pendientes" description="No hay productos por debajo de sus parámetros de reposición." />}</div></Card>; }
