import { useEffect, useState, type CSSProperties } from "react";
import { Bot, Boxes, BriefcaseBusiness, ChartNoAxesCombined, CircleDollarSign, ClipboardList, Handshake, Package, ReceiptText, ShoppingCart, Sparkles, Users, X } from "lucide-react";

const items = [["IA",Bot,-90],["Clientes",Users,-57],["Ventas",ShoppingCart,-24],["Finanzas",CircleDollarSign,9],["Caja",ReceiptText,42],["Compras",ClipboardList,75],["Inventario",Package,108],["CRM",Handshake,141],["Gestión",BriefcaseBusiness,174],["Datos",Boxes,207],["Insights",ChartNoAxesCombined,240]] as const;
const INTRO=2400, ORBIT=4400, CONVERGE=1800, WELCOME=2500, EXIT=2000, TOTAL=INTRO+ORBIT+CONVERGE+WELCOME+EXIT;

type Phase="intro"|"orbit"|"converge"|"welcome"|"exit";

export function NuvaLaunchExperience({onComplete}:{onComplete:()=>void}){
 const [visible,setVisible]=useState(false),[reduced,setReduced]=useState(false),[phase,setPhase]=useState<Phase>("intro");
 useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)"),r=media.matches;setReduced(r);setVisible(true);if(r){const t=window.setTimeout(()=>{setVisible(false);onComplete()},1400);return()=>window.clearTimeout(t)}const ts=[window.setTimeout(()=>setPhase("orbit"),INTRO),window.setTimeout(()=>setPhase("converge"),INTRO+ORBIT),window.setTimeout(()=>setPhase("welcome"),INTRO+ORBIT+CONVERGE),window.setTimeout(()=>setPhase("exit"),INTRO+ORBIT+CONVERGE+WELCOME),window.setTimeout(()=>{setVisible(false);onComplete()},TOTAL)];return()=>ts.forEach(window.clearTimeout)},[onComplete]);
 const finish=()=>{setPhase("exit");window.setTimeout(()=>{setVisible(false);onComplete()},EXIT)};
 if(!visible)return null;
 return <div aria-label="Bienvenido a Nüva One" aria-live="polite" className={`nuva-launch ${reduced?"nuva-launch--reduced":""} nuva-launch--${phase}`}>
 <style>{`
 .nuva-launch{--nuva-radius:clamp(155px,18vmin,270px);--nuva-stage-size:min(82vmin,760px);--nuva-core-size:clamp(150px,20vmin,230px);--nuva-module-scale:1;}
 .nuva-launch .nuva-launch__stage{width:var(--nuva-stage-size);height:var(--nuva-stage-size);max-width:100vw;max-height:100vh;position:relative;display:grid;place-items:center}
 .nuva-launch .nuva-launch__module{animation:none!important;will-change:transform,opacity,filter}.nuva-launch__orbit{transform-origin:center;will-change:transform;width:100%;height:100%;position:absolute;inset:0}
 .nuva-launch--intro .nuva-launch__module{opacity:0;filter:blur(14px);transform:translate(-50%,-50%) rotate(var(--nuva-angle)) translateY(0) rotate(calc(-1*var(--nuva-angle))) scale(.18);transition:opacity .9s,filter 1.1s,transform 1.3s cubic-bezier(.16,1,.3,1);transition-delay:var(--nuva-delay)}
 .nuva-launch--orbit .nuva-launch__orbit{animation:nuva-orbit-spin ${ORBIT}ms cubic-bezier(.37,0,.63,1) both}
 .nuva-launch--orbit .nuva-launch__module{opacity:1;filter:blur(0);transform:translate(-50%,-50%) rotate(var(--nuva-angle)) translateY(calc(-1*var(--nuva-radius))) rotate(calc(-1*var(--nuva-angle))) scale(var(--nuva-module-scale));transition:opacity .9s,filter 1s,transform 1.3s cubic-bezier(.16,1,.3,1);transition-delay:var(--nuva-delay);animation:nuva-module-counterspin ${ORBIT}ms linear both}
 .nuva-launch--converge .nuva-launch__orbit{animation:none}.nuva-launch--converge .nuva-launch__module{opacity:.04;filter:blur(7px);transform:translate(-50%,-50%) rotate(var(--nuva-angle)) translateY(0) rotate(calc(-1*var(--nuva-angle))) scale(.2);animation:none;transition:transform ${CONVERGE}ms cubic-bezier(.65,0,.25,1),opacity ${CONVERGE}ms ease,filter ${CONVERGE}ms ease;transition-delay:calc(var(--nuva-delay)*.08)}
 .nuva-launch--intro .nuva-launch__core{transform:scale(.8);opacity:.65}.nuva-launch--orbit .nuva-launch__core{transform:scale(1);opacity:1;transition:1s cubic-bezier(.16,1,.3,1)}.nuva-launch--converge .nuva-launch__core{transform:scale(1.12);opacity:1;transition:${CONVERGE}ms cubic-bezier(.16,1,.3,1)}.nuva-launch--welcome .nuva-launch__core{transform:scale(.62);opacity:.08;transition:.9s cubic-bezier(.22,1,.36,1)}
 .nuva-launch__core{width:var(--nuva-core-size);height:var(--nuva-core-size);position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);transform-origin:center}
 .nuva-launch--intro .nuva-launch__welcome,.nuva-launch--orbit .nuva-launch__welcome,.nuva-launch--converge .nuva-launch__welcome{opacity:0;visibility:hidden}.nuva-launch--welcome .nuva-launch__welcome{opacity:1;visibility:visible;animation:nuva-welcome-in .95s cubic-bezier(.16,1,.3,1) both}.nuva-launch--exit .nuva-launch__welcome{opacity:1;visibility:visible;animation:nuva-welcome-out ${EXIT}ms cubic-bezier(.22,1,.36,1) forwards}
 .nuva-launch--exit{animation:nuva-scene-out ${EXIT}ms cubic-bezier(.22,1,.36,1) forwards}.nuva-launch--exit .nuva-launch__ambient{animation:nuva-ambient-out ${EXIT}ms cubic-bezier(.22,1,.36,1) forwards}.nuva-launch--exit .nuva-launch__grid,.nuva-launch--exit .nuva-launch__light-beam,.nuva-launch--exit .nuva-launch__ring,.nuva-launch--exit .nuva-launch__orbit,.nuva-launch--exit .nuva-launch__core,.nuva-launch--exit .nuva-launch__tagline{opacity:.08;filter:blur(4px);transform:scale(1.05);transition:${EXIT}ms cubic-bezier(.22,1,.36,1)}
 .nuva-launch__welcome{position:absolute!important;top:50%!important;left:50%!important;z-index:30!important;width:min(94vw,1200px);transform:translate(-50%,-50%);text-align:center;pointer-events:none}.nuva-launch__welcome-title{font-size:clamp(3rem,8vw,7.4rem)!important;font-weight:800!important;line-height:1.02;letter-spacing:-.055em;color:#080812!important;text-shadow:0 3px 20px rgba(255,255,255,.98),0 0 50px rgba(139,92,246,.2)}.nuva-launch__welcome-subtitle{font-size:clamp(1rem,2.1vw,1.5rem)!important;margin-top:.8rem;color:#11111b!important;font-weight:600}
 @keyframes nuva-orbit-spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}
 @keyframes nuva-module-counterspin{0%{transform:translate(-50%,-50%) rotate(var(--nuva-angle)) translateY(calc(-1*var(--nuva-radius))) rotate(calc(-1*var(--nuva-angle))) rotate(0deg)}100%{transform:translate(-50%,-50%) rotate(var(--nuva-angle)) translateY(calc(-1*var(--nuva-radius))) rotate(calc(-1*var(--nuva-angle))) rotate(-360deg)}}
 @keyframes nuva-welcome-in{0%{opacity:0;transform:translate(-50%,-50%) scale(.84);filter:blur(18px)}55%{opacity:1;transform:translate(-50%,-50%) scale(1.015);filter:blur(0)}100%{opacity:1;transform:translate(-50%,-50%) scale(1);filter:blur(0)}}@keyframes nuva-welcome-out{0%{opacity:1;transform:translate(-50%,-50%) scale(1);filter:blur(0)}45%{opacity:.72;transform:translate(-50%,-50%) scale(1.012);filter:blur(1px)}100%{opacity:0;transform:translate(-50%,-50%) scale(1.045);filter:blur(10px)}}@keyframes nuva-scene-out{0%{opacity:1;transform:scale(1);filter:blur(0)}45%{opacity:.92;transform:scale(1.008);filter:blur(.5px)}100%{opacity:0;transform:scale(1.035);filter:blur(7px)}}@keyframes nuva-ambient-out{0%{opacity:1;transform:scale(1);filter:blur(0)}100%{opacity:0;transform:scale(1.12);filter:blur(12px)}}
 .nuva-launch--reduced{animation:none!important}.nuva-launch--reduced .nuva-launch__welcome{opacity:1!important;visibility:visible!important;animation:none!important}
 @media(max-width:900px){.nuva-launch{--nuva-radius:min(27vmin,205px);--nuva-stage-size:min(92vmin,620px);--nuva-core-size:clamp(145px,24vmin,200px);--nuva-module-scale:.94}}
 @media(max-width:640px){.nuva-launch{--nuva-radius:min(35vw,165px);--nuva-stage-size:min(100vw,100svh);--nuva-core-size:155px;--nuva-module-scale:1}.nuva-launch__stage{max-height:100svh}.nuva-launch__module{min-width:58px;gap:5px}.nuva-launch__module-icon{width:42px;height:42px;border-radius:13px}.nuva-launch__module-icon svg{width:19px;height:19px}.nuva-launch__module span{font-size:8px}.nuva-launch__welcome-title{font-size:clamp(2.6rem,12vw,4.6rem)!important}}
 @media(min-width:1600px){.nuva-launch{--nuva-radius:clamp(220px,17vmin,285px);--nuva-stage-size:min(78vmin,820px);--nuva-core-size:clamp(190px,19vmin,245px);--nuva-module-scale:.98}}
 @media(orientation:landscape) and (max-height:700px){.nuva-launch{--nuva-radius:min(26vmin,185px);--nuva-stage-size:min(84vmin,640px);--nuva-core-size:clamp(140px,22vmin,190px)}}
 `}</style>
 <div className="nuva-launch__ambient"/><div className="nuva-launch__grid"/><div className="nuva-launch__light-beam nuva-launch__light-beam--one"/><div className="nuva-launch__light-beam nuva-launch__light-beam--two"/><div className="nuva-launch__ring nuva-launch__ring--outer"/><div className="nuva-launch__ring nuva-launch__ring--inner"/>
 <div className="nuva-launch__stage"><div className="nuva-launch__orbit" aria-hidden="true">{items.map(([label,Icon,angle],index)=><div key={label} className="nuva-launch__module" style={{"--nuva-angle":`${angle}deg`,"--nuva-delay":`${index*95}ms`} as CSSProperties}><div className="nuva-launch__module-icon"><Icon/></div><span>{label}</span></div>)}</div><div className="nuva-launch__core"><div className="nuva-launch__core-halo"/><div className="nuva-launch__core-ring"/><div className="nuva-launch__core-pulse"/><div className="nuva-launch__logo"><span>Nüva</span><small>ONE</small></div><div className="nuva-launch__spark nuva-launch__spark--one"/><div className="nuva-launch__spark nuva-launch__spark--two"/></div><div className="nuva-launch__tagline"><Sparkles aria-hidden="true"/><span>Inteligencia para tu negocio</span></div><div className="nuva-launch__welcome"><div className="nuva-launch__welcome-title">Bienvenido a Nüva One</div><div className="nuva-launch__welcome-subtitle">Todo tu negocio. Una inteligencia.</div></div></div>
 <button type="button" aria-label="Omitir animación" onClick={finish} className="nuva-launch__skip"><X aria-hidden="true"/><span>Omitir</span></button></div>;
}