import { useMemo, useState } from "react";
import { BarChart3, RotateCcw, SlidersHorizontal } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { fmtCLP } from "@/lib/biz-data";

type SalesProductAnalyticsProps = { sales: any[]; products: any[] };
type Metric = "units" | "revenue" | "orders" | "margin";
type Period = "all" | "today" | "7d" | "30d" | "month" | "year" | "custom";
const PERIOD_LABELS: Record<Period, string> = { all: "Todo el historial", today: "Hoy", "7d": "Últimos 7 días", "30d": "Últimos 30 días", month: "Este mes", year: "Este año", custom: "Personalizado" };
function startForPeriod(period: Period, now: Date) { const start = new Date(now); start.setHours(0,0,0,0); if (period === "today") return start; if (period === "7d") { start.setDate(start.getDate()-6); return start; } if (period === "30d") { start.setDate(start.getDate()-29); return start; } if (period === "month") { start.setDate(1); return start; } if (period === "year") { start.setMonth(0,1); return start; } return null; }
function endForPeriod(period: Period, now: Date) { if (period === "custom" || period === "all") return null; const end = new Date(now); end.setHours(23,59,59,999); return end; }

export function SalesProductAnalytics({ sales, products }: SalesProductAnalyticsProps) {
  const [period,setPeriod]=useState<Period>("30d"); const [metric,setMetric]=useState<Metric>("units"); const [topN,setTopN]=useState("10"); const [channel,setChannel]=useState("all"); const [paymentMethod,setPaymentMethod]=useState("all"); const [status,setStatus]=useState("paid"); const [category,setCategory]=useState("all"); const [search,setSearch]=useState(""); const [customFrom,setCustomFrom]=useState(""); const [customTo,setCustomTo]=useState("");
  const categories=useMemo(()=>Array.from(new Set((products??[]).map(p=>p.category).filter((v):v is string=>Boolean(v)))).sort(),[products]);
  const productMap=useMemo(()=>{const map=new Map<string,any>(); (products??[]).forEach(p=>map.set(p.id,p)); return map;},[products]);
  const rows=useMemo(()=>{const now=new Date(); const start=period==="custom"&&customFrom?new Date(`${customFrom}T00:00:00`):startForPeriod(period,now); const end=period==="custom"&&customTo?new Date(`${customTo}T23:59:59`):endForPeriod(period,now); const grouped=new Map<string,{name:string;sku:string;category:string;units:number;revenue:number;orders:number;margin:number|null}>();
    for(const sale of sales??[]){ if(status!=="all"&&sale.status!==status)continue; if(channel!=="all"&&sale.channel!==channel)continue; if(paymentMethod!=="all"&&sale.payment_method!==paymentMethod)continue; const date=new Date(sale.sale_date); if(start&&date<start)continue; if(end&&date>end)continue;
      for(const item of Array.isArray(sale.items)?sale.items:[]){const product=item.product_id?productMap.get(item.product_id):undefined; const name=String(item.name||product?.name||"Producto sin nombre"); const productCategory=String(item.category||product?.category||"Sin categoría"); if(category!=="all"&&productCategory!==category)continue; if(search&&!`${name} ${product?.sku??""}`.toLowerCase().includes(search.toLowerCase()))continue; const key=String(item.product_id||`free:${name.toLowerCase()}`); const current=grouped.get(key)??{name,sku:String(product?.sku||"—"),category:productCategory,units:0,revenue:0,orders:0,margin:null}; const qty=Number(item.qty||0); const price=Number(item.price||0); const rawCost=item.cost??item.unit_cost??product?.cost??product?.cost_price??product?.purchase_price; const cost=rawCost==null||rawCost===""?null:Number(rawCost); current.units+=qty; current.revenue+=qty*price; current.orders+=1; if(cost!=null&&Number.isFinite(cost))current.margin=(current.margin??0)+(price-cost)*qty; grouped.set(key,current);}
    }
    return Array.from(grouped.values()).sort((a,b)=>metric==="revenue"?b.revenue-a.revenue:metric==="orders"?b.orders-a.orders:metric==="margin"?(b.margin??-Infinity)-(a.margin??-Infinity):b.units-a.units).slice(0,Number(topN));
  },[sales,products,productMap,period,customFrom,customTo,metric,topN,channel,paymentMethod,status,category,search]);
  const chartData=rows.map(row=>({...row,label:row.name.length>26?`${row.name.slice(0,26)}…`:row.name,value:metric==="revenue"?row.revenue:metric==="orders"?row.orders:metric==="margin"?(row.margin??0):row.units})); const metricLabel=metric==="revenue"?"Ingresos":metric==="orders"?"Ventas":metric==="margin"?"Margen":"Unidades"; const hasActiveFilters=period!=="30d"||metric!=="units"||topN!=="10"||channel!=="all"||paymentMethod!=="all"||status!=="paid"||category!=="all"||Boolean(search)||Boolean(customFrom)||Boolean(customTo);
  function resetFilters(){setPeriod("30d");setMetric("units");setTopN("10");setChannel("all");setPaymentMethod("all");setStatus("paid");setCategory("all");setSearch("");setCustomFrom("");setCustomTo("");}
  return <Card className="overflow-hidden"><div className="border-b p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary"><BarChart3 className="h-4 w-4"/> Análisis de ventas</div><h2 className="mt-1 text-xl font-semibold tracking-tight">Productos más vendidos</h2><p className="mt-1 text-sm text-muted-foreground">Identifica qué productos están moviendo unidades, ingresos y margen.</p></div>{hasActiveFilters&&<Button variant="ghost" size="sm" onClick={resetFilters}><RotateCcw className="mr-1.5 h-3.5 w-3.5"/> Restablecer</Button>}</div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><Label className="text-xs">Periodo</Label><Select value={period} onValueChange={v=>setPeriod(v as Period)}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(PERIOD_LABELS).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div><Label className="text-xs">Métrica</Label><Select value={metric} onValueChange={v=>setMetric(v as Metric)}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="units">Unidades vendidas</SelectItem><SelectItem value="revenue">Ingresos generados</SelectItem><SelectItem value="orders">Número de ventas</SelectItem><SelectItem value="margin">Margen generado</SelectItem></SelectContent></Select></div><div><Label className="text-xs">Ranking</Label><Select value={topN} onValueChange={setTopN}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="5">Top 5</SelectItem><SelectItem value="10">Top 10</SelectItem><SelectItem value="20">Top 20</SelectItem><SelectItem value="50">Top 50</SelectItem></SelectContent></Select></div><div><Label className="text-xs">Buscar producto / SKU</Label><Input className="mt-1" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar..."/></div></div>
    <div className="mt-3 flex items-center gap-2 text-xs font-medium text-muted-foreground"><SlidersHorizontal className="h-3.5 w-3.5"/> Filtros avanzados</div><div className="mt-2 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><Label className="text-xs">Canal</Label><Select value={channel} onValueChange={setChannel}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos los canales</SelectItem><SelectItem value="tienda">Tienda</SelectItem><SelectItem value="online">Online</SelectItem><SelectItem value="whatsapp">WhatsApp</SelectItem><SelectItem value="instagram">Instagram</SelectItem></SelectContent></Select></div><div><Label className="text-xs">Método de pago</Label><Select value={paymentMethod} onValueChange={setPaymentMethod}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos los métodos</SelectItem><SelectItem value="efectivo">Efectivo</SelectItem><SelectItem value="tarjeta">Tarjeta</SelectItem><SelectItem value="transferencia">Transferencia</SelectItem><SelectItem value="credito">Crédito</SelectItem></SelectContent></Select></div><div><Label className="text-xs">Estado de venta</Label><Select value={status} onValueChange={setStatus}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos</SelectItem><SelectItem value="paid">Pagadas</SelectItem><SelectItem value="pending">Pendientes</SelectItem><SelectItem value="draft">Borradores</SelectItem><SelectItem value="cancelled">Canceladas</SelectItem></SelectContent></Select></div><div><Label className="text-xs">Categoría</Label><Select value={category} onValueChange={setCategory}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas las categorías</SelectItem>{categories.map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div></div>
    {period==="custom"&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><div><Label className="text-xs">Desde</Label><Input className="mt-1" type="date" value={customFrom} onChange={e=>setCustomFrom(e.target.value)}/></div><div><Label className="text-xs">Hasta</Label><Input className="mt-1" type="date" value={customTo} onChange={e=>setCustomTo(e.target.value)}/></div></div>}
  </div><div className="p-5 md:p-6">{chartData.length===0?<div className="flex min-h-64 items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">No hay productos que coincidan con los filtros seleccionados.</div>:<div className="h-[360px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} layout="vertical" margin={{top:4,right:18,left:12,bottom:4}}><CartesianGrid horizontal={false} strokeDasharray="3 3"/><XAxis type="number" tickLine={false} axisLine={false} allowDecimals={false}/><YAxis type="category" dataKey="label" width={150} tickLine={false} axisLine={false}/><Tooltip cursor={{opacity:0.08}} formatter={(value:number)=>[metric==="units"||metric==="orders"?value.toLocaleString("es-CL"):fmtCLP(value),metricLabel]} labelFormatter={(_,payload)=>payload?.[0]?.payload?.name??"Producto"}/><Bar dataKey="value" name={metricLabel} radius={[0,6,6,0]} maxBarSize={28}/></BarChart></ResponsiveContainer></div>}
    {chartData.length>0&&<div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[620px] text-sm"><thead className="bg-muted/40 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">#</th><th className="px-4 py-3">Producto</th><th className="px-4 py-3">SKU</th><th className="px-4 py-3 text-right">Unidades</th><th className="px-4 py-3 text-right">Ingresos</th><th className="px-4 py-3 text-right">Margen</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${row.name}-${index}`} className="border-t"><td className="px-4 py-3 font-semibold">{index+1}</td><td className="px-4 py-3 font-medium">{row.name}</td><td className="px-4 py-3 text-muted-foreground">{row.sku}</td><td className="px-4 py-3 text-right tabular-nums">{row.units.toLocaleString("es-CL")}</td><td className="px-4 py-3 text-right tabular-nums">{fmtCLP(row.revenue)}</td><td className="px-4 py-3 text-right tabular-nums">{row.margin==null?"—":fmtCLP(row.margin)}</td></tr>)}</tbody></table></div>}</div></Card>;
}
