/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SelectBusinessRouteImport } from './routes/select-business'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedMfaRequiredRouteImport } from './routes/_authenticated/mfa-required'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as ApiQuotesFollowUpRouteImport } from './routes/api/quotes/follow-up'
import { Route as ApiNotificationsLowStockCheckRouteImport } from './routes/api/notifications/low-stock-check'
import { Route as ApiCollectionsCheckOverdueRouteImport } from './routes/api/collections/check-overdue'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingSiiProcessQueueRouteImport } from './routes/api/billing/sii/process-queue'
import { Route as ApiBillingSiiEmitBulkRouteImport } from './routes/api/billing/sii/emit-bulk'
import { Route as ApiBillingSiiEmitRouteImport } from './routes/api/billing/sii/emit'
import { Route as ApiBillingSiiConnectRouteImport } from './routes/api/billing/sii/connect'
import { Route as ApiBillingPaymentsWebhookRouteImport } from './routes/api/billing/payments/webhook'
import { Route as ApiBillingPaymentsCreateRouteImport } from './routes/api/billing/payments/create'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectBusinessRoute = SelectBusinessRouteImport.update({
  id: '/select-business',
  path: '/select-business',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMfaRequiredRoute =
  AuthenticatedMfaRequiredRouteImport.update({
    id: '/mfa-required',
    path: '/mfa-required',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesFollowUpRoute = ApiQuotesFollowUpRouteImport.update({
  id: '/api/quotes/follow-up',
  path: '/api/quotes/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsLowStockCheckRoute =
  ApiNotificationsLowStockCheckRouteImport.update({
    id: '/api/notifications/low-stock-check',
    path: '/api/notifications/low-stock-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectionsCheckOverdueRoute =
  ApiCollectionsCheckOverdueRouteImport.update({
    id: '/api/collections/check-overdue',
    path: '/api/collections/check-overdue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSiiProcessQueueRoute =
  ApiBillingSiiProcessQueueRouteImport.update({
    id: '/api/billing/sii/process-queue',
    path: '/api/billing/sii/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingSiiEmitBulkRoute = ApiBillingSiiEmitBulkRouteImport.update({
  id: '/api/billing/sii/emit-bulk',
  path: '/api/billing/sii/emit-bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSiiEmitRoute = ApiBillingSiiEmitRouteImport.update({
  id: '/api/billing/sii/emit',
  path: '/api/billing/sii/emit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSiiConnectRoute = ApiBillingSiiConnectRouteImport.update({
  id: '/api/billing/sii/connect',
  path: '/api/billing/sii/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPaymentsWebhookRoute =
  ApiBillingPaymentsWebhookRouteImport.update({
    id: '/api/billing/payments/webhook',
    path: '/api/billing/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingPaymentsCreateRoute =
  ApiBillingPaymentsCreateRouteImport.update({
    id: '/api/billing/payments/create',
    path: '/api/billing/payments/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-business': typeof SelectBusinessRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/mfa-required': typeof AuthenticatedMfaRequiredRoute
  '/pos': typeof AuthenticatedPosRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/collections/check-overdue': typeof ApiCollectionsCheckOverdueRoute
  '/api/notifications/low-stock-check': typeof ApiNotificationsLowStockCheckRoute
  '/api/quotes/follow-up': typeof ApiQuotesFollowUpRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/billing/payments/create': typeof ApiBillingPaymentsCreateRoute
  '/api/billing/payments/webhook': typeof ApiBillingPaymentsWebhookRoute
  '/api/billing/sii/connect': typeof ApiBillingSiiConnectRoute
  '/api/billing/sii/emit': typeof ApiBillingSiiEmitRoute
  '/api/billing/sii/emit-bulk': typeof ApiBillingSiiEmitBulkRoute
  '/api/billing/sii/process-queue': typeof ApiBillingSiiProcessQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-business': typeof SelectBusinessRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/mfa-required': typeof AuthenticatedMfaRequiredRoute
  '/pos': typeof AuthenticatedPosRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/collections/check-overdue': typeof ApiCollectionsCheckOverdueRoute
  '/api/notifications/low-stock-check': typeof ApiNotificationsLowStockCheckRoute
  '/api/quotes/follow-up': typeof ApiQuotesFollowUpRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/billing/payments/create': typeof ApiBillingPaymentsCreateRoute
  '/api/billing/payments/webhook': typeof ApiBillingPaymentsWebhookRoute
  '/api/billing/sii/connect': typeof ApiBillingSiiConnectRoute
  '/api/billing/sii/emit': typeof ApiBillingSiiEmitRoute
  '/api/billing/sii/emit-bulk': typeof ApiBillingSiiEmitBulkRoute
  '/api/billing/sii/process-queue': typeof ApiBillingSiiProcessQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-business': typeof SelectBusinessRoute
  '/terms': typeof TermsRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/mfa-required': typeof AuthenticatedMfaRequiredRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/collections/check-overdue': typeof ApiCollectionsCheckOverdueRoute
  '/api/notifications/low-stock-check': typeof ApiNotificationsLowStockCheckRoute
  '/api/quotes/follow-up': typeof ApiQuotesFollowUpRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/billing/payments/create': typeof ApiBillingPaymentsCreateRoute
  '/api/billing/payments/webhook': typeof ApiBillingPaymentsWebhookRoute
  '/api/billing/sii/connect': typeof ApiBillingSiiConnectRoute
  '/api/billing/sii/emit': typeof ApiBillingSiiEmitRoute
  '/api/billing/sii/emit-bulk': typeof ApiBillingSiiEmitBulkRoute
  '/api/billing/sii/process-queue': typeof ApiBillingSiiProcessQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/select-business'
    | '/terms'
    | '/ai'
    | '/analytics'
    | '/automations'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/mfa-required'
    | '/pos'
    | '/purchases'
    | '/quotes'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/api/chat'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/collections/check-overdue'
    | '/api/notifications/low-stock-check'
    | '/api/quotes/follow-up'
    | '/api/whatsapp/webhook'
    | '/api/billing/payments/create'
    | '/api/billing/payments/webhook'
    | '/api/billing/sii/connect'
    | '/api/billing/sii/emit'
    | '/api/billing/sii/emit-bulk'
    | '/api/billing/sii/process-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/select-business'
    | '/terms'
    | '/ai'
    | '/analytics'
    | '/automations'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/mfa-required'
    | '/pos'
    | '/purchases'
    | '/quotes'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/api/chat'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/collections/check-overdue'
    | '/api/notifications/low-stock-check'
    | '/api/quotes/follow-up'
    | '/api/whatsapp/webhook'
    | '/api/billing/payments/create'
    | '/api/billing/payments/webhook'
    | '/api/billing/sii/connect'
    | '/api/billing/sii/emit'
    | '/api/billing/sii/emit-bulk'
    | '/api/billing/sii/process-queue'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/select-business'
    | '/terms'
    | '/_authenticated/ai'
    | '/_authenticated/analytics'
    | '/_authenticated/automations'
    | '/_authenticated/billing'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/inventory'
    | '/_authenticated/mfa-required'
    | '/_authenticated/pos'
    | '/_authenticated/purchases'
    | '/_authenticated/quotes'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/shifts'
    | '/api/chat'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/collections/check-overdue'
    | '/api/notifications/low-stock-check'
    | '/api/quotes/follow-up'
    | '/api/whatsapp/webhook'
    | '/api/billing/payments/create'
    | '/api/billing/payments/webhook'
    | '/api/billing/sii/connect'
    | '/api/billing/sii/emit'
    | '/api/billing/sii/emit-bulk'
    | '/api/billing/sii/process-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectBusinessRoute: typeof SelectBusinessRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiCollectionsCheckOverdueRoute: typeof ApiCollectionsCheckOverdueRoute
  ApiNotificationsLowStockCheckRoute: typeof ApiNotificationsLowStockCheckRoute
  ApiQuotesFollowUpRoute: typeof ApiQuotesFollowUpRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiBillingPaymentsCreateRoute: typeof ApiBillingPaymentsCreateRoute
  ApiBillingPaymentsWebhookRoute: typeof ApiBillingPaymentsWebhookRoute
  ApiBillingSiiConnectRoute: typeof ApiBillingSiiConnectRoute
  ApiBillingSiiEmitRoute: typeof ApiBillingSiiEmitRoute
  ApiBillingSiiEmitBulkRoute: typeof ApiBillingSiiEmitBulkRoute
  ApiBillingSiiProcessQueueRoute: typeof ApiBillingSiiProcessQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-business': {
      id: '/select-business'
      path: '/select-business'
      fullPath: '/select-business'
      preLoaderRoute: typeof SelectBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mfa-required': {
      id: '/_authenticated/mfa-required'
      path: '/mfa-required'
      fullPath: '/mfa-required'
      preLoaderRoute: typeof AuthenticatedMfaRequiredRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/follow-up': {
      id: '/api/quotes/follow-up'
      path: '/api/quotes/follow-up'
      fullPath: '/api/quotes/follow-up'
      preLoaderRoute: typeof ApiQuotesFollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/low-stock-check': {
      id: '/api/notifications/low-stock-check'
      path: '/api/notifications/low-stock-check'
      fullPath: '/api/notifications/low-stock-check'
      preLoaderRoute: typeof ApiNotificationsLowStockCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections/check-overdue': {
      id: '/api/collections/check-overdue'
      path: '/api/collections/check-overdue'
      fullPath: '/api/collections/check-overdue'
      preLoaderRoute: typeof ApiCollectionsCheckOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/sii/process-queue': {
      id: '/api/billing/sii/process-queue'
      path: '/api/billing/sii/process-queue'
      fullPath: '/api/billing/sii/process-queue'
      preLoaderRoute: typeof ApiBillingSiiProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/sii/emit-bulk': {
      id: '/api/billing/sii/emit-bulk'
      path: '/api/billing/sii/emit-bulk'
      fullPath: '/api/billing/sii/emit-bulk'
      preLoaderRoute: typeof ApiBillingSiiEmitBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/sii/emit': {
      id: '/api/billing/sii/emit'
      path: '/api/billing/sii/emit'
      fullPath: '/api/billing/sii/emit'
      preLoaderRoute: typeof ApiBillingSiiEmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/sii/connect': {
      id: '/api/billing/sii/connect'
      path: '/api/billing/sii/connect'
      fullPath: '/api/billing/sii/connect'
      preLoaderRoute: typeof ApiBillingSiiConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/payments/webhook': {
      id: '/api/billing/payments/webhook'
      path: '/api/billing/payments/webhook'
      fullPath: '/api/billing/payments/webhook'
      preLoaderRoute: typeof ApiBillingPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/payments/create': {
      id: '/api/billing/payments/create'
      path: '/api/billing/payments/create'
      fullPath: '/api/billing/payments/create'
      preLoaderRoute: typeof ApiBillingPaymentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMfaRequiredRoute: typeof AuthenticatedMfaRequiredRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMfaRequiredRoute: AuthenticatedMfaRequiredRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectBusinessRoute: SelectBusinessRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiCollectionsCheckOverdueRoute: ApiCollectionsCheckOverdueRoute,
  ApiNotificationsLowStockCheckRoute: ApiNotificationsLowStockCheckRoute,
  ApiQuotesFollowUpRoute: ApiQuotesFollowUpRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiBillingPaymentsCreateRoute: ApiBillingPaymentsCreateRoute,
  ApiBillingPaymentsWebhookRoute: ApiBillingPaymentsWebhookRoute,
  ApiBillingSiiConnectRoute: ApiBillingSiiConnectRoute,
  ApiBillingSiiEmitRoute: ApiBillingSiiEmitRoute,
  ApiBillingSiiEmitBulkRoute: ApiBillingSiiEmitBulkRoute,
  ApiBillingSiiProcessQueueRoute: ApiBillingSiiProcessQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
