/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SelectBusinessRouteImport } from './routes/select-business'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NegociosIndexRouteImport } from './routes/negocios/index'
import { Route as ForoIndexRouteImport } from './routes/foro/index'
import { Route as ForoTopicIdRouteImport } from './routes/foro/$topicId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedMfaRequiredRouteImport } from './routes/_authenticated/mfa-required'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as ApiQuotesFollowUpRouteImport } from './routes/api/quotes/follow-up'
import { Route as ApiNotificationsLowStockCheckRouteImport } from './routes/api/notifications/low-stock-check'
import { Route as ApiCollectionsCheckOverdueRouteImport } from './routes/api/collections/check-overdue'
import { Route as ApiBillingSubscribeRunChargesRouteImport } from './routes/api/billing/subscribe/run-charges'
import { Route as ApiBillingSubscribeRegisterRouteImport } from './routes/api/billing/subscribe/register'
import { Route as ApiBillingSubscribeCancelRouteImport } from './routes/api/billing/subscribe/cancel'
import { Route as ApiBillingSubscribeCallbackRouteImport } from './routes/api/billing/subscribe/callback'
import { Route as ApiBillingPaymentsWebhookRouteImport } from './routes/api/billing/payments/webhook'
import { Route as ApiBillingPaymentsDisconnectRouteImport } from './routes/api/billing/payments/disconnect'
import { Route as ApiBillingPaymentsCreateRouteImport } from './routes/api/billing/payments/create'
import { Route as ApiBillingPaymentsConnectRouteImport } from './routes/api/billing/payments/connect'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectBusinessRoute = SelectBusinessRouteImport.update({
  id: '/select-business',
  path: '/select-business',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosIndexRoute = NegociosIndexRouteImport.update({
  id: '/negocios/',
  path: '/negocios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForoIndexRoute = ForoIndexRouteImport.update({
  id: '/foro/',
  path: '/foro/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForoTopicIdRoute = ForoTopicIdRouteImport.update({
  id: '/foro/$topicId',
  path: '/foro/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMfaRequiredRoute =
  AuthenticatedMfaRequiredRouteImport.update({
    id: '/mfa-required',
    path: '/mfa-required',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesFollowUpRoute = ApiQuotesFollowUpRouteImport.update({
  id: '/api/quotes/follow-up',
  path: '/api/quotes/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsLowStockCheckRoute =
  ApiNotificationsLowStockCheckRouteImport.update({
    id: '/api/notifications/low-stock-check',
    path: '/api/notifications/low-stock-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectionsCheckOverdueRoute =
  ApiCollectionsCheckOverdueRouteImport.update({
    id: '/api/collections/check-overdue',
    path: '/api/collections/check-overdue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingSubscribeRunChargesRoute =
  ApiBillingSubscribeRunChargesRouteImport.update({
    id: '/api/billing/subscribe/run-charges',
    path: '/api/billing/subscribe/run-charges',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingSubscribeRegisterRoute =
  ApiBillingSubscribeRegisterRouteImport.update({
    id: '/api/billing/subscribe/register',
    path: '/api/billing/subscribe/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingSubscribeCancelRoute =
  ApiBillingSubscribeCancelRouteImport.update({
    id: '/api/billing/subscribe/cancel',
    path: '/api/billing/subscribe/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingSubscribeCallbackRoute =
  ApiBillingSubscribeCallbackRouteImport.update({
    id: '/api/billing/subscribe/callback',
    path: '/api/billing/subscribe/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingPaymentsWebhookRoute =
  ApiBillingPaymentsWebhookRouteImport.update({
    id: '/api/billing/payments/webhook',
    path: '/api/billing/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingPaymentsDisconnectRoute =
  ApiBillingPaymentsDisconnectRouteImport.update({
    id: '/api/billing/payments/disconnect',
    path: '/api/billing/payments/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingPaymentsCreateRoute =
  ApiBillingPaymentsCreateRouteImport.update({
    id: '/api/billing/payments/create',
    path: '/api/billing/payments/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingPaymentsConnectRoute =
  ApiBillingPaymentsConnectRouteImport.update({
    id: '/api/billing/payments/connect',
    path: '/api/billing/payments/connect',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-business': typeof SelectBusinessRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/mfa-required': typeof AuthenticatedMfaRequiredRoute
  '/pos': typeof AuthenticatedPosRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/api/chat': typeof ApiChatRoute
  '/foro/$topicId': typeof ForoTopicIdRoute
  '/foro/': typeof ForoIndexRoute
  '/negocios/': typeof NegociosIndexRoute
  '/api/collections/check-overdue': typeof ApiCollectionsCheckOverdueRoute
  '/api/notifications/low-stock-check': typeof ApiNotificationsLowStockCheckRoute
  '/api/quotes/follow-up': typeof ApiQuotesFollowUpRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/billing/payments/connect': typeof ApiBillingPaymentsConnectRoute
  '/api/billing/payments/create': typeof ApiBillingPaymentsCreateRoute
  '/api/billing/payments/disconnect': typeof ApiBillingPaymentsDisconnectRoute
  '/api/billing/payments/webhook': typeof ApiBillingPaymentsWebhookRoute
  '/api/billing/subscribe/callback': typeof ApiBillingSubscribeCallbackRoute
  '/api/billing/subscribe/cancel': typeof ApiBillingSubscribeCancelRoute
  '/api/billing/subscribe/register': typeof ApiBillingSubscribeRegisterRoute
  '/api/billing/subscribe/run-charges': typeof ApiBillingSubscribeRunChargesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-business': typeof SelectBusinessRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/mfa-required': typeof AuthenticatedMfaRequiredRoute
  '/pos': typeof AuthenticatedPosRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/api/chat': typeof ApiChatRoute
  '/foro/$topicId': typeof ForoTopicIdRoute
  '/foro': typeof ForoIndexRoute
  '/negocios': typeof NegociosIndexRoute
  '/api/collections/check-overdue': typeof ApiCollectionsCheckOverdueRoute
  '/api/notifications/low-stock-check': typeof ApiNotificationsLowStockCheckRoute
  '/api/quotes/follow-up': typeof ApiQuotesFollowUpRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/billing/payments/connect': typeof ApiBillingPaymentsConnectRoute
  '/api/billing/payments/create': typeof ApiBillingPaymentsCreateRoute
  '/api/billing/payments/disconnect': typeof ApiBillingPaymentsDisconnectRoute
  '/api/billing/payments/webhook': typeof ApiBillingPaymentsWebhookRoute
  '/api/billing/subscribe/callback': typeof ApiBillingSubscribeCallbackRoute
  '/api/billing/subscribe/cancel': typeof ApiBillingSubscribeCancelRoute
  '/api/billing/subscribe/register': typeof ApiBillingSubscribeRegisterRoute
  '/api/billing/subscribe/run-charges': typeof ApiBillingSubscribeRunChargesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-business': typeof SelectBusinessRoute
  '/terms': typeof TermsRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/mfa-required': typeof AuthenticatedMfaRequiredRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/api/chat': typeof ApiChatRoute
  '/foro/$topicId': typeof ForoTopicIdRoute
  '/foro/': typeof ForoIndexRoute
  '/negocios/': typeof NegociosIndexRoute
  '/api/collections/check-overdue': typeof ApiCollectionsCheckOverdueRoute
  '/api/notifications/low-stock-check': typeof ApiNotificationsLowStockCheckRoute
  '/api/quotes/follow-up': typeof ApiQuotesFollowUpRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/billing/payments/connect': typeof ApiBillingPaymentsConnectRoute
  '/api/billing/payments/create': typeof ApiBillingPaymentsCreateRoute
  '/api/billing/payments/disconnect': typeof ApiBillingPaymentsDisconnectRoute
  '/api/billing/payments/webhook': typeof ApiBillingPaymentsWebhookRoute
  '/api/billing/subscribe/callback': typeof ApiBillingSubscribeCallbackRoute
  '/api/billing/subscribe/cancel': typeof ApiBillingSubscribeCancelRoute
  '/api/billing/subscribe/register': typeof ApiBillingSubscribeRegisterRoute
  '/api/billing/subscribe/run-charges': typeof ApiBillingSubscribeRunChargesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/select-business'
    | '/terms'
    | '/ai'
    | '/analytics'
    | '/automations'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/mfa-required'
    | '/pos'
    | '/purchases'
    | '/quotes'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/api/chat'
    | '/foro/$topicId'
    | '/foro/'
    | '/negocios/'
    | '/api/collections/check-overdue'
    | '/api/notifications/low-stock-check'
    | '/api/quotes/follow-up'
    | '/api/whatsapp/webhook'
    | '/api/billing/payments/connect'
    | '/api/billing/payments/create'
    | '/api/billing/payments/disconnect'
    | '/api/billing/payments/webhook'
    | '/api/billing/subscribe/callback'
    | '/api/billing/subscribe/cancel'
    | '/api/billing/subscribe/register'
    | '/api/billing/subscribe/run-charges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/select-business'
    | '/terms'
    | '/ai'
    | '/analytics'
    | '/automations'
    | '/billing'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/mfa-required'
    | '/pos'
    | '/purchases'
    | '/quotes'
    | '/sales'
    | '/settings'
    | '/shifts'
    | '/api/chat'
    | '/foro/$topicId'
    | '/foro'
    | '/negocios'
    | '/api/collections/check-overdue'
    | '/api/notifications/low-stock-check'
    | '/api/quotes/follow-up'
    | '/api/whatsapp/webhook'
    | '/api/billing/payments/connect'
    | '/api/billing/payments/create'
    | '/api/billing/payments/disconnect'
    | '/api/billing/payments/webhook'
    | '/api/billing/subscribe/callback'
    | '/api/billing/subscribe/cancel'
    | '/api/billing/subscribe/register'
    | '/api/billing/subscribe/run-charges'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/select-business'
    | '/terms'
    | '/_authenticated/ai'
    | '/_authenticated/analytics'
    | '/_authenticated/automations'
    | '/_authenticated/billing'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/inventory'
    | '/_authenticated/mfa-required'
    | '/_authenticated/pos'
    | '/_authenticated/purchases'
    | '/_authenticated/quotes'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/shifts'
    | '/api/chat'
    | '/foro/$topicId'
    | '/foro/'
    | '/negocios/'
    | '/api/collections/check-overdue'
    | '/api/notifications/low-stock-check'
    | '/api/quotes/follow-up'
    | '/api/whatsapp/webhook'
    | '/api/billing/payments/connect'
    | '/api/billing/payments/create'
    | '/api/billing/payments/disconnect'
    | '/api/billing/payments/webhook'
    | '/api/billing/subscribe/callback'
    | '/api/billing/subscribe/cancel'
    | '/api/billing/subscribe/register'
    | '/api/billing/subscribe/run-charges'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectBusinessRoute: typeof SelectBusinessRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ForoTopicIdRoute: typeof ForoTopicIdRoute
  ForoIndexRoute: typeof ForoIndexRoute
  NegociosIndexRoute: typeof NegociosIndexRoute
  ApiCollectionsCheckOverdueRoute: typeof ApiCollectionsCheckOverdueRoute
  ApiNotificationsLowStockCheckRoute: typeof ApiNotificationsLowStockCheckRoute
  ApiQuotesFollowUpRoute: typeof ApiQuotesFollowUpRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiBillingPaymentsConnectRoute: typeof ApiBillingPaymentsConnectRoute
  ApiBillingPaymentsCreateRoute: typeof ApiBillingPaymentsCreateRoute
  ApiBillingPaymentsDisconnectRoute: typeof ApiBillingPaymentsDisconnectRoute
  ApiBillingPaymentsWebhookRoute: typeof ApiBillingPaymentsWebhookRoute
  ApiBillingSubscribeCallbackRoute: typeof ApiBillingSubscribeCallbackRoute
  ApiBillingSubscribeCancelRoute: typeof ApiBillingSubscribeCancelRoute
  ApiBillingSubscribeRegisterRoute: typeof ApiBillingSubscribeRegisterRoute
  ApiBillingSubscribeRunChargesRoute: typeof ApiBillingSubscribeRunChargesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-business': {
      id: '/select-business'
      path: '/select-business'
      fullPath: '/select-business'
      preLoaderRoute: typeof SelectBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/': {
      id: '/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof NegociosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foro/': {
      id: '/foro/'
      path: '/foro'
      fullPath: '/foro/'
      preLoaderRoute: typeof ForoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foro/$topicId': {
      id: '/foro/$topicId'
      path: '/foro/$topicId'
      fullPath: '/foro/$topicId'
      preLoaderRoute: typeof ForoTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mfa-required': {
      id: '/_authenticated/mfa-required'
      path: '/mfa-required'
      fullPath: '/mfa-required'
      preLoaderRoute: typeof AuthenticatedMfaRequiredRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/follow-up': {
      id: '/api/quotes/follow-up'
      path: '/api/quotes/follow-up'
      fullPath: '/api/quotes/follow-up'
      preLoaderRoute: typeof ApiQuotesFollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/low-stock-check': {
      id: '/api/notifications/low-stock-check'
      path: '/api/notifications/low-stock-check'
      fullPath: '/api/notifications/low-stock-check'
      preLoaderRoute: typeof ApiNotificationsLowStockCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections/check-overdue': {
      id: '/api/collections/check-overdue'
      path: '/api/collections/check-overdue'
      fullPath: '/api/collections/check-overdue'
      preLoaderRoute: typeof ApiCollectionsCheckOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/subscribe/run-charges': {
      id: '/api/billing/subscribe/run-charges'
      path: '/api/billing/subscribe/run-charges'
      fullPath: '/api/billing/subscribe/run-charges'
      preLoaderRoute: typeof ApiBillingSubscribeRunChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/subscribe/register': {
      id: '/api/billing/subscribe/register'
      path: '/api/billing/subscribe/register'
      fullPath: '/api/billing/subscribe/register'
      preLoaderRoute: typeof ApiBillingSubscribeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/subscribe/cancel': {
      id: '/api/billing/subscribe/cancel'
      path: '/api/billing/subscribe/cancel'
      fullPath: '/api/billing/subscribe/cancel'
      preLoaderRoute: typeof ApiBillingSubscribeCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/subscribe/callback': {
      id: '/api/billing/subscribe/callback'
      path: '/api/billing/subscribe/callback'
      fullPath: '/api/billing/subscribe/callback'
      preLoaderRoute: typeof ApiBillingSubscribeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/payments/webhook': {
      id: '/api/billing/payments/webhook'
      path: '/api/billing/payments/webhook'
      fullPath: '/api/billing/payments/webhook'
      preLoaderRoute: typeof ApiBillingPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/payments/disconnect': {
      id: '/api/billing/payments/disconnect'
      path: '/api/billing/payments/disconnect'
      fullPath: '/api/billing/payments/disconnect'
      preLoaderRoute: typeof ApiBillingPaymentsDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/payments/create': {
      id: '/api/billing/payments/create'
      path: '/api/billing/payments/create'
      fullPath: '/api/billing/payments/create'
      preLoaderRoute: typeof ApiBillingPaymentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/payments/connect': {
      id: '/api/billing/payments/connect'
      path: '/api/billing/payments/connect'
      fullPath: '/api/billing/payments/connect'
      preLoaderRoute: typeof ApiBillingPaymentsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMfaRequiredRoute: typeof AuthenticatedMfaRequiredRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMfaRequiredRoute: AuthenticatedMfaRequiredRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectBusinessRoute: SelectBusinessRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ForoTopicIdRoute: ForoTopicIdRoute,
  ForoIndexRoute: ForoIndexRoute,
  NegociosIndexRoute: NegociosIndexRoute,
  ApiCollectionsCheckOverdueRoute: ApiCollectionsCheckOverdueRoute,
  ApiNotificationsLowStockCheckRoute: ApiNotificationsLowStockCheckRoute,
  ApiQuotesFollowUpRoute: ApiQuotesFollowUpRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiBillingPaymentsConnectRoute: ApiBillingPaymentsConnectRoute,
  ApiBillingPaymentsCreateRoute: ApiBillingPaymentsCreateRoute,
  ApiBillingPaymentsDisconnectRoute: ApiBillingPaymentsDisconnectRoute,
  ApiBillingPaymentsWebhookRoute: ApiBillingPaymentsWebhookRoute,
  ApiBillingSubscribeCallbackRoute: ApiBillingSubscribeCallbackRoute,
  ApiBillingSubscribeCancelRoute: ApiBillingSubscribeCancelRoute,
  ApiBillingSubscribeRegisterRoute: ApiBillingSubscribeRegisterRoute,
  ApiBillingSubscribeRunChargesRoute: ApiBillingSubscribeRunChargesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
