create table if not exists public.ops_agent_audit_runs (
  id bigint generated by default as identity primary key,
  protocol text not null,
  status text not null check (status in ('PASS','WARN','FAIL')),
  duration_ms integer,
  evidence jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.ops_agent_audit_runs enable row level security;

drop policy if exists "ops_agent_audit_runs_deny_public" on public.ops_agent_audit_runs;
create policy "ops_agent_audit_runs_deny_public"
  on public.ops_agent_audit_runs
  as restrictive
  for all
  to public
  using (false)
  with check (false);

create index if not exists idx_ops_agent_audit_runs_created_at
  on public.ops_agent_audit_runs (created_at desc);

comment on table public.ops_agent_audit_runs is
  'Read-only health audit evidence produced by the Nüva Agency control plane.';
