ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS pos_reference TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_business_pos_reference
  ON public.sales (business_id, pos_reference)
  WHERE pos_reference IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sales_business_payment_method
  ON public.sales (business_id, payment_method, sale_date);

CREATE OR REPLACE FUNCTION public.validate_sale_inventory()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  item JSONB;
  pid UUID;
  requested_qty INTEGER;
  available_qty INTEGER;
BEGIN
  IF NEW.total IS NULL OR NEW.total <= 0 THEN
    RAISE EXCEPTION 'SALE_TOTAL_INVALID';
  END IF;

  IF NEW.status IN ('paid','pending') AND NOT COALESCE(NEW.stock_applied, false) THEN
    FOR item IN SELECT * FROM jsonb_array_elements(COALESCE(NEW.items, '[]'::jsonb)) LOOP
      IF NULLIF(item->>'product_id','') IS NOT NULL THEN
        pid := (item->>'product_id')::uuid;
        requested_qty := GREATEST(COALESCE((item->>'qty')::integer, 0), 0);
        IF requested_qty <= 0 THEN
          RAISE EXCEPTION 'SALE_ITEM_QUANTITY_INVALID';
        END IF;

        SELECT stock INTO available_qty
        FROM public.products
        WHERE id = pid AND business_id = NEW.business_id
        FOR UPDATE;

        IF NOT FOUND THEN
          RAISE EXCEPTION 'SALE_PRODUCT_NOT_FOUND';
        END IF;

        IF available_qty < requested_qty THEN
          RAISE EXCEPTION 'SALE_INSUFFICIENT_STOCK:%:%', pid, available_qty;
        END IF;
      END IF;
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_sale_inventory ON public.sales;
CREATE TRIGGER trg_validate_sale_inventory
  BEFORE INSERT OR UPDATE OF status, items, total
  ON public.sales
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_sale_inventory();

COMMENT ON COLUMN public.sales.pos_reference IS 'Optional idempotency reference generated by POS checkout.';
